import type { Build } from './types';

/* AI 섹션에서 따로 여는 글.
   본체가 업무 시스템인 작업은 프로젝트 글 안에 묻히면 AI 를 무엇을 어떻게 붙였는지가
   안 읽힌다. 그래서 그 부분만 떼어 자기 글로 두고, partOf 로 원래 시스템을 가리킨다.
   사내 AI 플랫폼은 전체가 AI 작업이라 여기 두지 않고 프로젝트 글을 그대로 쓴다. */
export const aiWorks: Build[] = [
  {
    slug: 'expense-receipt-ai',
    title: 'AI 영수증 자동입력',
    category: 'AI',
    org: 'GlobalZeus',
    role: '1인 풀스택',
    period: '2026. 6 ~ 2026. 7',
    tech: 'OpenAI API · Next.js · Node.js · MSSQL',
    partOf: { title: '경비지출관리 시스템', href: '/projects/expense-management' },
    blocks: [
      { type: 'image', src: '/projects/expense-management/141.png', alt: 'AI 영수증 자동입력 화면' },
      { type: 'heading', text: '개요' },
      { type: 'paragraph', text: '경비를 처리하려면 계정과 용도를 골라야 하는데, 회계 계정은 익숙하지 않으면 고르기 어렵습니다. 이 입력을 AI가 대신 채웁니다.' },
      { type: 'paragraph', text: '쓸 수 있는 재료가 있었습니다. 이전 시스템이 4년 9개월 동안 처리한 이력 3.7만 건은 사람이 직접 고른 계정이 붙어 있는 데이터고, 영수증 원본도 4.5만 장이 남아 있었습니다. 그래서 모델부터 부르지 않고, 이 이력을 먼저 쓰기로 했습니다.' },
      { type: 'heading', text: '추천 순서' },
      { type: 'paragraph', text: '영수증이 들어오면 과거 이력을 먼저 조회하고, 비전 모델의 판독 결과를 그 위에 얹어 계정 후보 두세 개를 냅니다. 최종 선택은 사람이 합니다. 자동으로 확정해 버리면 잘못 분류된 전표를 아무도 못 잡기 때문입니다.' },
      { type: 'paragraph', text: '이력은 본인, 부서, 전사 세 범위로 나눠 셉니다. 같은 가맹점이라도 사람마다 처리 관행이 다르고, 전사 물량이 많다고 그쪽으로 끌려가면 본인 이력이 묻힙니다. 본인 이력이 두 건 이상이면 본인 기준으로, 그렇지 않고 부서 이력이 세 건 이상이면 부서 기준으로 순위를 정합니다.' },
      { type: 'paragraph', text: '이력만으로는 처음 가는 가맹점을 추천할 수 없어서 비전 판독으로 메우고, 반대로 모든 건을 모델에 태우면 비용과 시간이 늘어나서 이력을 앞에 둡니다. 둘 중 하나만으로는 안 되는 구조라 순서를 이렇게 잡았습니다.' },
      { type: 'heading', text: '출력 형식 제약' },
      { type: 'paragraph', text: '모델에게 자유롭게 답하게 두면 회사에 없는 계정명을 지어내거나 표기가 흔들립니다. 그래서 응답을 JSON 스키마로 강제하고, 계정 항목은 회사가 실제로 쓰는 16종 목록 안에서만 고르게 했습니다. 프롬프트로 부탁하는 방식과 달리 목록 밖 값이 나오는 것 자체가 불가능합니다.' },
      { type: 'paragraph', text: '후보 목록은 상황에 따라 더 줄입니다. 경상개발비처럼 특정 부서만 쓰는 계정은 그 부서가 아니면 목록에서 아예 빼서, 고를 수 없는 것을 고민하지 않게 했습니다.' },
      { type: 'heading', text: '응답 속도와 비용' },
      { type: 'paragraph', text: '회사 분류 기준처럼 매번 같은 지침은 프롬프트 앞에 고정하고 영수증과 신청자 정보만 뒤에 붙였습니다. 같은 앞부분이 캐시로 재사용되면서, 입력 토큰의 94%가 캐시에서 나오고 응답 지연은 절반으로 줄었습니다. 영수증 이미지 리사이즈와 추론 옵션도 함께 낮췄습니다.' },
      { type: 'paragraph', text: '호출마다 모델, 토큰, 캐시 적중, 지연, 비용과 사용자가 최종 채택한 계정을 로그로 남깁니다. 추천이 실제로 맞았는지는 채택 여부로만 알 수 있습니다.' },
      { type: 'heading', text: '모바일' },
      { type: 'image', src: '/projects/expense-management/157.png', alt: '모바일 영수증 촬영 화면' },
      { type: 'image', src: '/projects/expense-management/158.png', alt: '모바일 자동입력 결과 화면' },
      { type: 'paragraph', text: '모바일에서는 영수증 촬영, AI 자동입력, 결재상신으로 이어지는 흐름에 맞춰 카드형 리스트와 풀스크린 시트 구조의 화면을 구현했습니다.' },
    ],
  },
  {
    slug: 'bi-nl-query',
    title: '자연어 데이터 조회',
    category: 'AI',
    org: 'GlobalZeus',
    role: '1인 풀스택',
    period: '2026. 5 ~ 진행중',
    tech: 'OpenAI API · Next.js · Node.js · MSSQL',
    partOf: { title: '사내 BI 플랫폼', href: '/projects/bi' },
    blocks: [
      { type: 'image', src: '/projects/bi/166.png', alt: '자연어 데이터 조회 진입 화면', caption: '자연어로 묻고 리포트로 받는 자리' },
      { type: 'heading', text: '개요' },
      { type: 'paragraph', text: '리포트를 직접 구성하지 않아도 되도록, 자연어 질문을 받아 알맞은 데이터셋과 차원, 측정값을 골라 조회하고 결과를 미리보기 표로 돌려주는 기능을 붙이고 있습니다.' },
      { type: 'image', src: '/projects/bi/164.png', alt: '자연어 데이터 조회 입력 화면' },
      { type: 'heading', text: '조회 범위' },
      { type: 'paragraph', text: 'LLM 이 하는 일은 도구 하나를 호출해 데이터셋과 차원, 측정값, 필터를 고르는 데까지입니다. SQL 을 쓰게 두지 않아, 조회가 등록된 메타 밖으로 나가지 않습니다.' },
      { type: 'heading', text: '검증과 재시도' },
      { type: 'paragraph', text: '고른 값이 실제로 있는지는 모델이 아니라 코드가 판정합니다. 데이터셋 코드가 메타에 없거나, 차원과 측정값이 그 데이터셋에 등록된 것이 아니면 거부합니다. 하나도 고르지 않은 경우도 막습니다. 빈 채로 통과시키면 미리보기 화면에서 레이아웃 오류로 터집니다.' },
      { type: 'paragraph', text: '거부할 때 실패로 끝내지 않고, 그 데이터셋에서 쓸 수 있는 코드 목록을 오류 메시지에 담아 모델에게 돌려줍니다. 무엇이 틀렸는지와 대신 쓸 수 있는 것을 함께 주면 다음 호출에서 스스로 고칩니다.' },
      { type: 'heading', text: '미리보기' },
      { type: 'paragraph', text: '검증을 통과한 구성으로 조회하고 결과는 30행까지만 미리보기로 내려보냅니다. 모델에게는 그중 다섯 행만 보여 줍니다. 답변 문장을 쓰는 데는 그 정도로 충분해서, 전체 결과를 프롬프트에 밀어 넣지 않습니다.' },
      { type: 'image', src: '/projects/bi/165.png', alt: '자연어 조회 결과 미리보기 표' },
    ],
  },
  {
    slug: 'editor-ai-writing',
    title: 'AI 작성',
    category: 'AI',
    org: 'GlobalZeus',
    role: '1인 풀스택',
    tech: 'Tiptap · ProseMirror · Next.js · Node.js',
    partOf: { title: '공용 에디터와 문서뷰어', href: '/archive/shared-editor-viewer' },
    blocks: [
      { type: 'image', src: '/projects/shared-editor-viewer/242.png', alt: '에디터 툴바의 AI 작성 드롭다운', caption: '툴바의 AI 작성 - 초안·이어쓰기·요약을 그 자리에서 고릅니다' },
      { type: 'heading', text: '개요' },
      { type: 'paragraph', text: '글을 다듬거나 맞춤법을 봐 달라는 건 사람들이 AI 에게 가장 자주 시키는 일입니다. 그런데 그러려면 본문을 복사해 다른 창에 붙여넣고, 나온 글을 다시 가져와야 합니다.' },
      { type: 'paragraph', text: '그래서 글을 쓸 때 늘 열어 두는 에디터 안에 넣었습니다. 상용 에디터를 붙여 쓰는 동안에는 안쪽에 손댈 수 없어 깔끔하게 붙일 방법이 없었는데, 에디터를 새로 만들면서 쓰던 흐름 그대로 이어지게 넣을 수 있었습니다.' },
      { type: 'heading', text: '동작' },
      { type: 'paragraph', text: '툴바 드롭다운에는 초안 작성, 이어쓰기, 문단형 요약, 불릿형 요약을 두고, 본문을 선택하면 그 자리에 다듬기가 뜹니다. 쓰던 흐름을 끊지 않으려고 선택 기반 동작은 툴바까지 올라가지 않게 했습니다.' },
      { type: 'image', src: '/projects/shared-editor-viewer/244.png', alt: '본문을 선택하면 뜨는 편집 도구', caption: '본문을 끌어 선택하면 그 자리에 도구가 뜹니다' },
      { type: 'paragraph', text: '초안에는 회의록·업무보고·체크리스트·결정사항 정리 프리셋을 붙였고, 다듬기는 짧게·길게·맞춤법 교정·격식 있게·부드럽게로 나눴습니다.' },
      { type: 'image', src: '/projects/shared-editor-viewer/243.png', alt: 'AI 초안 작성 패널', caption: '초안 작성 - 자주 쓰는 문서 꼴을 프리셋으로 둡니다' },
      { type: 'heading', text: '패널' },
      { type: 'paragraph', text: '패널은 툴바 바로 아래에 인라인으로 열립니다. 모달로 띄우면 본문이 가려져서, 나온 글과 원래 글을 나란히 두고 비교할 수 없기 때문입니다. 생성되는 글은 스트리밍으로 흘리고, 미리보기는 요청한 사람 화면에만 둡니다. 여럿이 함께 고치는 문서에서는 완성 전 출력이 남에게 보이면 안 되기 때문입니다.' },
      { type: 'image', src: '/projects/shared-editor-viewer/245.png', alt: 'AI 다듬기 결과 미리보기', caption: '다듬은 결과와 원래 문장을 위아래로 두고 고릅니다' },
      { type: 'paragraph', text: '나온 글은 고른 자리를 대체하거나 그 아래에 넣습니다. 둘 중 무엇을 할지는 사용자가 정하고, 고르기 전까지 본문은 그대로입니다. 이어서 시킬 만한 것도 몇 개 같이 띄워, 매번 지시를 처음부터 쓰지 않게 했습니다.' },
      { type: 'heading', text: '앱 중립' },
      { type: 'paragraph', text: '에디터는 여러 시스템이 함께 쓰는 공용 컴포넌트라, 앱마다 엔드포인트를 만들지 않고 하나로 두었습니다. 무엇을 할지는 동작 이름으로, 어디서 불렀는지는 출처로 넘깁니다. 출처는 모델에 줄 문맥과 로그에만 쓰고 권한 판정에는 쓰지 않습니다.' },
    ],
  },
];
