import type { Build } from './types';

export const builds: Build[] = [
  {
    slug: 'expense-management',
    title: '경비지출관리 시스템',
    category: 'Enterprise System',
    org: 'GlobalZeus',
    role: '1인 풀스택',
    period: '2026. 6 ~ 현재',
    tech: 'Next.js · Node.js · MSSQL · OpenAI API',
    blocks: [
      { type: 'image', src: '/projects/expense-management/134.png', alt: '법인카드 경비 조회 화면', caption: '경비 조회와 청구 - 법인카드' },
      { type: 'heading', text: '개요' },
      { type: 'paragraph', text: '그룹웨어를 전환하면서 경비 처리 업무를 옮겨올 사내 시스템이 필요했습니다. 기존에는 RPA가 ERP 전표 입력을 대신하고 있었는데, 실행 환경을 많이 타는 데다 오류도 잦았습니다. 그래서 법인카드 사용내역 확인부터 계정 매핑, 전자결재 상신, ERP 회계전표 생성까지를 하나의 흐름으로 묶은 경비지출관리 시스템을 구축했습니다.' },
      { type: 'paragraph', text: '목표는 사용자가 카드 내역을 골라 용도만 입력하면 회계 전표는 시스템이 만들도록 하는 것이었습니다. 그러려면 사람이 하던 계정 분류와 ERP 전표 입력을 시스템이 대신할 수 있어야 했고, 이 두 가지가 프로젝트의 중심 과제가 됐습니다.' },
      { type: 'heading', text: '법인카드 경비 처리' },
      { type: 'paragraph', text: 'ERP에 매일 적재되는 카드 사용내역을 실시간으로 연동해, 내 카드의 거래를 건별 처리 상태와 함께 확인하는 화면을 만들었습니다. 카드와 사원이 N:N으로 매핑되는 권한 구조를 그대로 반영했습니다.' },
      { type: 'paragraph', text: '입력은 최대한 줄이는 방향으로 설계했습니다. 회계 계정과목을 직접 고르게 하면 비전공자에게는 어려운 선택이 되기 때문에, 경비 처리에 실제로 쓰이는 계정만 화이트리스트로 추리고 세목 선택지는 ERP 계정 정의에서 동적으로 파생되도록 했습니다. 연구 부서의 지출이 경상개발비 계정으로 치환되는 사내 회계 규칙, 전표 귀속 부서를 현재가 아닌 회계일 당시의 발령 이력으로 잡는 규칙 같은 도메인 지식도 로직에 담았습니다.' },
      { type: 'image', src: '/projects/expense-management/159.png', alt: '법인카드 처리 모달 - 계정과목과 부가세, 적요 입력', caption: '법인카드 처리 - 거래를 골라 계정과목과 부가세, 적요를 입력하고 결재상신으로 이어집니다' },
      { type: 'image', src: '/projects/expense-management/135.png', alt: '개인경비 등록 화면 - 계정과목 선택 후 전체 입력폼', caption: '개인경비 등록 - 계정과목을 고르면 세목과 거래처, 금액 입력란이 이어집니다' },
      { type: 'paragraph', text: '개인경비와 일반영수증도 같은 입력 구조 위에 얹어, 영수증 첨부 → 회계일, 거래처, 금액 입력 → 저장과 상신으로 이어지게 했습니다. 상신 이후의 결재 현황을 모아 보는 화면은 다음 단계인 결재 연동과 함께 채울 예정입니다.' },
      { type: 'heading', text: 'ERP 전표 자동생성 엔진' },
      { type: 'image', src: '/projects/expense-management/160.png', alt: 'ERP 전표 자동생성 엔진 흐름도', caption: '경비 청구가 ERP 회계 전표가 되기까지 - 검증과 채번, 저장이 한 트랜잭션으로 묶입니다.' },
      { type: 'paragraph', text: '이 프로젝트에서 가장 공을 들인 부분입니다. ERP의 전표 저장 로직은 문서가 없어서, 네이티브 ERP가 실제로 처리한 전표의 트레이스를 확보해 내부 저장 프로시저를 하나씩 분석했습니다. 그렇게 분개 생성 → 전표 저장 → 카드 피드 연동 → 기표마감 검증으로 이어지는 전표 자동생성 엔진을 만들었습니다.' },
      { type: 'paragraph', text: '회계 데이터는 "거의 맞음"이 허용되지 않기 때문에, 개발 단계의 검증 기준을 네이티브 ERP와의 행 단위 비교(diff=0)로 잡았습니다. 같은 거래를 엔진과 네이티브 ERP가 각각 처리한 결과가 완전히 일치해야 통과입니다. 이 과정에서 ERP 내부 채번 테이블과 동기화하지 않으면 이후 네이티브 저장이 깨질 수 있다는 것도 발견해 함께 해결했고, 운영 중에는 저장할 때마다 차변과 대변의 합계와 전표 소유권을 검증합니다.' },
      { type: 'paragraph', text: 'ERP를 단일 진실 소스로 두고 시스템은 캐시처럼 동작하게 했습니다. ERP 쪽에서 전표가 삭제되거나 연결이 어긋나도 다음 저장 시점에 스스로 복구하고, 마감된 달에는 저장이 거부되고, 결재가 진행 중인 전표는 잠깁니다. 만드는 것보다 운영 중에 깨지지 않는 것에 비중을 둔 설계입니다.' },
      { type: 'heading', text: 'AI 영수증 자동입력' },
      { type: 'image', src: '/projects/expense-management/141.png', alt: 'AI 영수증 분석 화면 - 계정과목 후보와 근거, 적요 제안', caption: 'AI 추천 - 영수증을 분석해 계정과목 후보와 근거, 적요까지 제안 (샘플 영수증)' },
      { type: 'paragraph', text: '영수증을 보고 계정과 용도를 고르는 일은 번거로운 작업이라, AI가 대신 채워주면 실제로 잘 쓰이겠다는 생각에서 시작했습니다. 비전 모델이 영수증을 분석한 결과에, 과거 지출 이력 3.7만 건을 적재해 만든 이력 기반 추천을 우선순위로 병합하는 다단계 추천 구조로 만들었습니다. 부가세 공제 여부처럼 규칙화하기 어려운 항목은 2년치 카드 전표에서 계정별 처리 관행을 집계해 기본값을 정합니다.' },
      { type: 'paragraph', text: '입력 보조 기능은 느리면 쓰지 않게 되기 때문에, 영수증 이미지 리사이즈와 프롬프트 캐싱, 추론 옵션 조정으로 응답 지연을 줄였습니다. 영수증의 사업자번호가 ERP 거래처와 정확히 1건 매칭되면 거래처까지 자동으로 채워지고, 호출마다 토큰과 비용, 사용자가 최종 채택한 계정을 로그로 남겨 추천 품질을 추적합니다.' },
      { type: 'heading', text: '모바일' },
      { type: 'image', src: '/projects/expense-management/157.png', alt: '모바일 법인카드 내역 화면', caption: '모바일 법인카드 내역은 카드형 리스트로 보여줍니다.' },
      { type: 'image', src: '/projects/expense-management/158.png', alt: '모바일 개인경비 등록 화면', caption: '모바일에서는 등록 폼이 풀스크린 시트로 열립니다. (샘플 데이터)' },
      { type: 'paragraph', text: '모바일에서 가장 가치 있는 시나리오는 영수증을 그 자리에서 찍어 바로 상신하는 것이라고 봤습니다. 데스크톱에서는 영수증을 스캔해 옮겨야 하지만 모바일에는 카메라가 바로 있기 때문입니다. 촬영 → AI 자동입력 → 결재상신 흐름에 맞춰 카드형 리스트와 풀스크린 시트 구조의 모바일 화면을 만들었습니다.' },
      { type: 'paragraph', text: '목록과 화면 셸은 모바일 전용 컴포넌트로 분리했지만, ERP 연동의 핵심 로직이 담긴 입력 폼은 복제하지 않았습니다. 복제하면 이후 모든 수정이 두 벌이 되기 때문에, 폼은 한 벌을 유지한 채 모바일에서는 풀스크린 시트로 열리도록 했습니다.' },
    ],
  },
  {
    slug: 'work-app-platform',
    title: '업무 앱 제작 플랫폼',
    category: 'No-Code Platform',
    org: 'GlobalZeus',
    role: '1인 풀스택',
    period: '2026. 5 ~ 현재',
    tech: 'Next.js · Node.js · MSSQL · Redis · Elasticsearch',
    blocks: [
      { type: 'image', src: '/projects/work-app-platform/145.png', alt: '메인 화면 - 전체 앱 카탈로그', caption: '메인 화면 - 전체 앱 카탈로그' },
      { type: 'heading', text: '개요' },
      { type: 'paragraph', text: '그룹웨어를 전환하면서 다우오피스 Works로 만들어 쓰던 사내 업무 앱들을 대체할 플랫폼이 필요했습니다. 코드 없이 입력 양식과 목록, 프로세스를 정의해 업무 앱을 만드는 노코드 플랫폼을 구축했습니다.' },
      { type: 'paragraph', text: '같은 기능을 복제하는 대신, 기존 Works에서 부족했던 기능을 보완하고 사내 결재 시스템과의 연동을 더하는 방향으로 재설계했습니다. 기존 다우오피스 Applet의 마이그레이션도 함께 지원해 레거시 데이터까지 옮겨올 수 있게 했습니다.' },
      { type: 'image', src: '/projects/work-app-platform/161.png', alt: '업무 앱 플랫폼 구조 다이어그램', caption: '앱 정의가 곧 스키마가 됩니다. 문서는 EAV 구조로 저장되어 필드를 바꿔도 테이블 구조는 바뀌지 않습니다.' },
      { type: 'heading', text: '앱 생성' },
      { type: 'subheading', text: '템플릿' },
      { type: 'image', src: '/projects/work-app-platform/146.png', alt: '템플릿 선택 화면' },
      { type: 'paragraph', text: '자주 쓰이는 양식은 17종의 템플릿 카탈로그에서 골라 바로 시작할 수 있습니다. 빈 화면에서 시작하는 부담을 줄이기 위한 장치입니다. 템플릿은 스냅샷 버전으로 관리해 재발행 이력이 남고, 기존 앱을 통째로 복제해 시작할 수도 있습니다.' },
      { type: 'subheading', text: '기본정보' },
      { type: 'image', src: '/projects/work-app-platform/147.png', alt: '앱 기본정보 설정 화면' },
      { type: 'paragraph', text: '사용자가 직접 업무 앱을 만드는 진입 화면입니다. 앱 아이콘은 글리프·컬러 아이콘과 배경색을 조합해 커스터마이징할 수 있습니다.' },
      { type: 'subheading', text: '입력화면 (폼 빌더)' },
      { type: 'image', src: '/projects/work-app-platform/148.png', alt: '폼 빌더 화면' },
      { type: 'paragraph', text: '플랫폼의 핵심인 폼 빌더입니다. 코드 없이 약 30종의 필드로 입력 양식을 설계할 수 있고, 기본 필드 외에 에디터와 외부 DB SELECT 쿼리를 연동하는 필드를 제공합니다.' },
      { type: 'paragraph', text: '쿼리 안에 같은 폼의 다른 필드 값을 {필드명} 토큰으로 끼워 넣을 수 있어, 앞 필드의 선택에 따라 뒷 필드의 선택지가 바뀌는 양식도 코드 없이 만들 수 있습니다. 사용자 정의 쿼리를 받는 만큼 SELECT 이외 구문과 시스템 오브젝트 접근을 차단하는 다층 검열과 실행 시간과 행 수 제한을 서버에 두었습니다.' },
      { type: 'paragraph', text: '필드 값을 계산식으로 채우는 수식 필드, 고유값과 충돌 제약을 정의해두면 입력 중에 실시간으로 경고하는 중복과 충돌 규칙 엔진도 함께 제공합니다.' },
      { type: 'subheading', text: '목록화면' },
      { type: 'image', src: '/projects/work-app-platform/149.png', alt: '목록 설정 화면', caption: '목록 설정 화면' },
      { type: 'image', src: '/projects/work-app-platform/150.png', alt: '목록 화면 - 테이블', caption: '목록 화면 - 테이블' },
      { type: 'image', src: '/projects/work-app-platform/88.png', alt: '목록 화면 - 보드', caption: '목록 화면 - 보드' },
      { type: 'paragraph', text: '목록은 테이블과 보드(칸반) 외에 캘린더와 타임라인 뷰로도 전환해 볼 수 있습니다. 보드는 프로세스 상태가 곧 칸반 컬럼이라 드래그로 상태를 옮깁니다. 날짜나 기간 필드가 있는 앱은 캘린더 뷰로 바꾸면 월간 달력과 리소스별 타임라인으로 같은 데이터를 볼 수 있어서, 예약이나 일정을 다루는 앱에 그대로 씁니다. 상단에는 막대, 라인, 파이, 도넛, 게이지, 트리맵 등 9종 차트로 구성하는 차트 보드가 표시되고, 어떤 필드를 어떤 차트로 볼지는 사용자가 직접 정합니다.' },
      { type: 'image', src: '/projects/work-app-platform/163.png', alt: '캘린더 뷰 - 법인차량 예약 타임라인', caption: '캘린더 뷰 - 법인차량 예약을 차량별 타임라인으로' },
      { type: 'subheading', text: '프로세스 관리' },
      { type: 'image', src: '/projects/work-app-platform/151.png', alt: '프로세스(워크플로우) 설정 화면', caption: '상태와 전환 규칙 정의' },
      { type: 'paragraph', text: '상태 머신(워크플로우)을 정의하는 화면입니다. 사용자가 만든 워크플로우는 저장할 때 서버에서 정합성을 검증합니다. 빈 상태, 연결되지 않은 전이, 중복 액션, 시작 상태 누락 같은 오류가 운영에 반영되지 않도록 막는 방어 장치입니다.' },
      { type: 'paragraph', text: '조건을 정의해두면 충족되는 순간 상태가 스스로 이동하는 자동 전환도 지원합니다. 담당자가 상태 옮기는 것을 잊어 흐름이 멈추는 일을 줄이기 위한 기능입니다.' },
      { type: 'paragraph', text: '자동 전환은 잘못 쓰면 상태가 무한히 도는 사고로 이어질 수 있어 방어 로직에 공을 들였습니다. 연쇄 전이 중 이미 지나온 상태로는 되돌아가지 못하게 루프를 차단하고, 전환 조건을 바꾸면 기존 문서 전체를 청크 단위로 다시 평가해 정합성을 맞춥니다. 바꿔도 다음 저장 때 곧바로 자동 이탈할 상태로의 수동 변경은 애초에 막습니다.' },
      { type: 'subheading', text: '접근 제어' },
      { type: 'image', src: '/projects/work-app-platform/152.png', alt: '접근 제어 설정 화면' },
      { type: 'paragraph', text: '공유 범위, 역할 기반 권한, 운영자 지정, 목록 필터를 조합해 접근을 제어합니다. 여기에 문서 단위 비공개와 앱 단위 비공개 옵션을 함께 둔 것은, 공유받은 사용자라도 민감한 문서는 등록자와 운영자만 볼 수 있어야 하는 경우가 실제로 있었기 때문입니다.' },
      { type: 'subheading', text: '설정' },
      { type: 'image', src: '/projects/work-app-platform/153.png', alt: '앱 관리 화면' },
      { type: 'paragraph', text: '앱이 운영 단계로 들어서면 필요해지는 기능들을 한 화면에 모았습니다. 앱 정의(폼, 목록, 프로세스, 접근제어)와 운영 시점의 부가 기능을 카드로 분리해 배치했습니다.' },
      { type: 'heading', text: '앱 간 데이터 연동' },
      { type: 'image', src: '/projects/work-app-platform/91.png', alt: '앱 간 데이터 참조 - 공개 컴포넌트 설정 화면', caption: '앱 간 데이터 참조 - 다른 앱에 노출할 컴포넌트를 필드 단위로 설정합니다' },
      { type: 'image', src: '/projects/work-app-platform/92.png', alt: '앱 간 참조 관계 시각화 화면' },
      { type: 'paragraph', text: '같은 데이터를 여러 앱에서 중복 입력하는 것을 막기 위해 앱 간 데이터 참조를 만들었습니다. 검색 기준 필드와 표시 필드를 운영자가 직접 매핑하고, 앱 간 양방향 참조 관계를 시각화하는 관리 화면도 함께 두었습니다. 참조는 역방향으로도 볼 수 있어, 문서 상세에서 이 문서를 참조하는 다른 앱의 문서들을 확인할 수 있습니다.' },
      { type: 'heading', text: '데이터 복사' },
      { type: 'paragraph', text: '비슷한 문서를 반복 작성하는 수고를 줄이기 위한 복사 기능입니다. 그대로 복제하는 대신 필드 타입 호환을 따져 자동 매핑하고, 사용자가 조정한 매핑은 저장해 다음 복사에 재사용합니다. 다른 앱의 문서를 끌어와 새 문서로 만드는 것도 같은 구조로 처리됩니다.' },
      { type: 'heading', text: '데이터 일괄 등록' },
      { type: 'image', src: '/projects/work-app-platform/154.png', alt: '데이터 일괄 등록 화면' },
      { type: 'paragraph', text: 'CSV 파일로 여러 건을 한 번에 등록할 수 있습니다. 대용량 파일이 서비스 응답을 막지 않도록 백그라운드 워커 구조로 처리합니다.' },
      { type: 'heading', text: '데이터 목록 다운로드' },
      { type: 'image', src: '/projects/work-app-platform/155.png', alt: '다운로드 이력 화면', caption: '누가 어떤 필터로 무엇을 내려받았는지 다운로드 이력으로 남습니다.' },
      { type: 'paragraph', text: '다운로드는 비동기 큐와 청크 처리로 설계했습니다. 대량 데이터도 서비스 응답을 막지 않고, 진행 상태는 이력 화면에서 주기적으로 갱신되어 확인할 수 있습니다.' },
      { type: 'paragraph', text: '다운로드 이력을 남겨 누가 언제 어떤 데이터를 받았는지 사후에 추적할 수 있게 했습니다. 사내 데이터 반출 감사를 염두에 둔 결정입니다.' },
      { type: 'heading', text: '외부 데이터 가져오기 (API Key)' },
      { type: 'image', src: '/projects/work-app-platform/156.png', alt: 'API Key 발급 화면', caption: 'API 인증키 발급과 필드 파라미터 매핑' },
      { type: 'paragraph', text: '외부 시스템이 Works 앱으로 데이터를 자동으로 등록하고 갱신할 수 있도록 앱별 API Key를 발급하고 필드별 파라미터를 매핑하는 구조를 만들었습니다. 어떤 시스템이든 같은 인터페이스로 데이터를 보낼 수 있습니다.' },
      { type: 'heading', text: '결재 연동' },
      { type: 'image', src: '/projects/work-app-platform/97.png', alt: '결재 연동 설정 화면' },
      { type: 'image', src: '/projects/work-app-platform/98.png', alt: '결재 상신 화면' },
      { type: 'image', src: '/projects/work-app-platform/99.png', alt: '결재 문서 화면' },
      { type: 'paragraph', text: 'Works 앱에서 작성한 문서를 별도 입력 없이 그대로 사내 결재로 상신할 수 있습니다. 노코드로 만든 앱이 실제 업무 흐름에 연결되는 지점이고, 기존 Works와 가장 차별화되는 부분입니다.' },
      { type: 'heading', text: '문서 협업' },
      { type: 'paragraph', text: '문서마다 댓글과 대댓글로 논의를 이어갈 수 있고, 댓글에도 파일을 첨부할 수 있습니다. 첨부 파일은 임시 업로드 후 문서 저장 시점에 확정되는 2단계 구조라, 작성을 취소한 문서의 파일이 서버에 남지 않습니다.' },
      { type: 'paragraph', text: '사용자가 남기는 활동기록과 별개로, 시스템이 자동 기록하는 변경이력을 두었습니다. 필드 단위로 변경 전후 값을 남기는 수정 불가능한 로그라, 누가 언제 무엇을 바꿨는지를 사후에 정확히 추적할 수 있습니다.' },
      { type: 'heading', text: '알림' },
      { type: 'paragraph', text: '문서 생성과 수정, 상태 변경, 댓글, 연동 신청 등 8종 이벤트를 알림으로 발송합니다. 공을 들인 부분은 수신자 결정입니다. 작성자, 운영자, 즐겨찾기 사용자 같은 역할 후보와 사용자별 구독 설정을 교차해 받을 사람을 계산하고, 조직도에 없는 퇴사자는 제외합니다.' },
      { type: 'paragraph', text: '발송은 아웃박스에 쌓아 워커가 처리하는 구조로, 알림 실패가 문서 저장에 영향을 주지 않습니다. 메일과 사내 메신저 카드로 멀티 채널 발송되고, 알림 인프라에 문제가 생겨도 발송 자체가 막히지 않도록 조회 실패 시의 동작까지 정의해 두었습니다.' },
      { type: 'heading', text: '회사 폴더' },
      { type: 'image', src: '/projects/work-app-platform/100.png', alt: '회사 폴더 화면' },
      { type: 'image', src: '/projects/work-app-platform/101.png', alt: '회사 폴더 권한 설정 화면' },
      { type: 'paragraph', text: '개인이 만든 앱과 회사가 공식 운영하는 앱을 구분하기 위해 회사 폴더를 두었습니다. 폴더는 관리자만 편집할 수 있고, 폴더 단위로 부서와 사용자별 권한과 공개 여부를 설정합니다.' },
      { type: 'heading', text: '통합검색' },
      { type: 'paragraph', text: '앱이 늘어날수록 문서가 어느 앱에 있는지 찾는 일이 문제가 되기 때문에, 모든 앱의 문서를 가로질러 찾는 Elasticsearch 통합 검색을 만들었습니다. 문서 변경은 outbox에 쌓아 동기화 워커가 색인을 갱신하는 구조라, 본 데이터와 검색 색인이 어긋나지 않습니다.' },
      { type: 'heading', text: '모바일' },
      { type: 'image', src: '/projects/work-app-platform/162.png', alt: '모바일 앱 카탈로그 화면', caption: '앱 카탈로그와 검색' },
      { type: 'image', src: '/projects/work-app-platform/164.png', alt: '모바일 문서 작성 화면', caption: '문서 작성' },
      { type: 'image', src: '/projects/work-app-platform/165.png', alt: '모바일 캘린더 뷰 화면', caption: '캘린더 뷰' },
      { type: 'paragraph', text: '조회, 작성, 검색 같은 핵심 동선은 전용 모바일 레이아웃으로 처리합니다. 앱 설계처럼 데스크톱이 필요한 화면은 모바일에서 진입하면 안내 화면으로 막아, 어중간하게 깨진 화면을 보여주지 않습니다.' },
    ],
  },
  {
    slug: 'oneplace',
    title: 'ZEUS OnePlace (사내 통합 포털)',
    category: 'Enterprise Portal',
    org: 'GlobalZeus',
    role: '1인 풀스택',
    period: '2026. 5 ~ 현재',
    tech: 'Next.js · Node.js · MSSQL · Capacitor',
    blocks: [
      { type: 'image', src: '/projects/oneplace/136.png', alt: '홈 대시보드 화면', caption: '홈 대시보드' },
      { type: 'heading', text: '개요' },
      { type: 'paragraph', text: '흩어져 있는 사내 서비스의 입구를 하나로 모으는 통합 포털을 구축했습니다. 임직원이 하루를 시작하는 첫 화면을 목표로, 사용자별로 구성되는 개인 대시보드로 설계했습니다.' },
      { type: 'paragraph', text: '같은 웹 한 벌로 PC와 모바일 브라우저를 함께 커버하는 것을 아키텍처 전략으로 잡았습니다.' },
      { type: 'heading', text: '홈 대시보드' },
      { type: 'paragraph', text: '인사 배너, 즐겨찾기, 최근 사용 메뉴, 알림, 연차 현황, 오늘 근무시간 요약, 날씨까지, 임직원이 자주 확인하는 정보를 한 화면에 모았습니다. 다른 시스템에 들어가야 보이던 것들을 첫 화면으로 끌어온 것입니다.' },
      { type: 'heading', text: '전사 서비스 메뉴' },
      { type: 'image', src: '/projects/oneplace/137.png', alt: '전체 서비스 메뉴 화면', caption: '전체 서비스 메뉴' },
      { type: 'paragraph', text: '전사 서비스로 이동하는 사이트맵과 사용자별 즐겨찾기와 최근 메뉴를 제공합니다. 메뉴는 관리자 화면에서 회사 스코프와 공개 범위를 걸어 관리하므로, 소속 회사와 권한에 따라 보이는 메뉴가 달라집니다.' },
      { type: 'heading', text: '알림 센터' },
      { type: 'image', src: '/projects/oneplace/144.png', alt: '알림 수신 설정 화면', caption: '알림은 서비스와 채널 단위로 끄고 켤 수 있습니다.' },
      { type: 'paragraph', text: '여러 사내 시스템의 알림을 한곳에 모았습니다. 카테고리 탭과 무한 스크롤로 조회하는데, 페이지 번호 대신 keyset 페이징을 적용해 조회 중에 새 알림이 유입돼도 목록이 밀리거나 중복되지 않습니다. 수신 설정은 카테고리보다 세밀한 앱과 이벤트 단위로 두었고, 수신 채널과 방해금지 시간대까지 사용자가 직접 정합니다.' },
      { type: 'heading', text: '모바일 앱' },
      { type: 'image', src: '/projects/oneplace/142.png', alt: '모바일 앱 홈 화면', caption: '모바일 앱 셸 - 홈' },
      { type: 'image', src: '/projects/oneplace/143.png', alt: '모바일 앱 알림 화면', caption: '모바일 앱 셸 - 받은 알림' },
      { type: 'paragraph', text: '앱은 네이티브로 다시 만들지 않았습니다. 화면을 두 벌로 유지하는 비용을 피하려고, 배포된 웹을 Capacitor WebView 셸로 감싸 설치형 앱으로 만드는 쪽을 택했습니다. 웹이 SSR이라 정적 번들을 내장하는 대신 원격 URL을 로드하는 방식을 썼고, 이동 가능한 도메인은 화이트리스트로 제한했습니다.' },
      { type: 'paragraph', text: '앱 여부는 User-Agent 토큰으로 판별합니다. 같은 웹이지만 앱에서 열리면 로그인이 사내 SSO(OIDC)로 분기되고, 하단 탭바 중심의 모바일 셸 UI가 적용됩니다. 원격 URL을 로드하는 구조 덕에 웹만 배포하면 앱은 스토어 재배포 없이 갱신됩니다.' },
      { type: 'paragraph', text: '웹뷰 특유의 어긋남도 다뤘습니다. 모바일에서의 메뉴 이동은 SPA 전환 대신 전체 페이지 이동으로 처리해 하드웨어 뒤로가기가 히스토리와 어긋나지 않게 했고, 외부 서비스 링크는 웹뷰에 가두지 않고 시스템 브라우저로 내보냅니다.' },
    ],
  },
  {
    slug: 'bi',
    title: '사내 BI 플랫폼',
    category: 'BI Platform',
    org: 'GlobalZeus',
    role: '1인 풀스택',
    period: '2026. 5 ~ 현재',
    tech: 'Next.js · Node.js · MSSQL · Recharts · dnd-kit',
    blocks: [
      { type: 'image', src: '/projects/bi/102.png', alt: '포털 홈 화면', caption: '포털 홈 화면' },
      { type: 'heading', text: '개요' },
      { type: 'paragraph', text: '상용 BI 솔루션에 준하는 풀 BI 플랫폼을 구현하고 있습니다. 차원과 측정값을 끌어다 리포트를 만드는 디자이너(저작), 만든 리포트를 조회하는 뷰어(런타임), 폴더, 권한, 검색을 갖춘 포털까지가 범위입니다. 유료 라이브러리 없이 OSS만으로 만드는 것을 목표로 하고 있고, OLAP 피벗 그리드도 직접 구현하고 있습니다.' },
      { type: 'paragraph', text: '속도보다 견고함을 우선하는 것을 원칙으로 잡았습니다. 그리드와 디자이너처럼 복잡한 컴포넌트는 회귀가 생기기 쉬워서, 각 단계를 안정화한 뒤에만 다음 단계로 넘어갔고 백엔드와 프론트를 합쳐 660개가 넘는 테스트로 검증하며 진행했습니다.' },
      { type: 'heading', text: 'OLAP 피벗 그리드' },
      { type: 'image', src: '/projects/bi/104.png', alt: '피벗 그리드 리포트 화면', caption: '사업부 × 연도 피벗 리포트' },
      { type: 'paragraph', text: '플랫폼의 중심 컴포넌트입니다. 행과 열 다중 차원, 소계와 총계, 셀 포맷, 정렬, 드릴다운을 지원하는 피벗 그리드를 라이브러리 없이 구현했습니다. 렌더링은 Canvas와 DOM 사이에서 고민했는데, 접근성과 React 생태계와의 결합을 위해 가상 스크롤 DOM 방식을 택해 10만 행 규모까지 처리하도록 했습니다.' },
      { type: 'heading', text: '쿼리 엔진' },
      { type: 'image', src: '/projects/bi/162.png', alt: 'BI 쿼리 엔진 파이프라인 다이어그램', caption: '리포트 정의가 SQL이 되기까지 - 등록된 메타만 통과하고, 값은 전부 파라미터로 바인딩됩니다.' },
      { type: 'paragraph', text: '프론트가 차원, 측정값, 필터를 JSON으로 보내면 백엔드가 SQL을 동적 생성해 DW를 조회합니다. 사용자 입력이 SQL이 되는 구조인 만큼 식별자는 메타 DB에 등록된 컬럼만 화이트리스트로 허용하고 값은 전부 파라미터 바인딩으로 처리해, 인젝션이 끼어들 여지를 구조적으로 차단했습니다.' },
      { type: 'paragraph', text: '결과는 LRU 캐시에 얹고, 새벽 스케줄 잡이 등록된 리포트를 미리 계산해 영속 캐시에 쌓아둡니다. 자주 보는 리포트가 DW를 거치지 않고 열리게 하기 위해서입니다. 기본 집계 외에 비율이나 차이를 정의하는 계산식 측정값과 누적 집계도 지원하고, 부서 체계와 다른 분석 단위가 필요할 때를 위해 사용자가 직접 조직을 묶는 개인 분석조직 그룹을 쿼리 시점에 CASE 식으로 주입되는 동적 차원으로 만들었습니다.' },
      { type: 'heading', text: '시맨틱 모델 (메타 관리)' },
      { type: 'image', src: '/projects/bi/105.png', alt: '데이터셋 메타 관리 화면', caption: '데이터셋 메타 관리 화면' },
      { type: 'paragraph', text: '분석 대상은 데이터셋, 차원, 측정값 메타로 등록해 관리합니다. 메타를 수정하면 쿼리 엔진에 즉시 반영되므로, 새 분석 주제를 추가할 때 코드 배포가 필요 없습니다. 삭제가 기존 리포트를 깨뜨리지 않도록, 차원이나 측정값을 지우기 전에 사용 중인 리포트를 검사해 경고하는 방어 장치도 두었습니다.' },
      { type: 'heading', text: '리포트 뷰어와 디자이너' },
      { type: 'image', src: '/projects/bi/103.png', alt: '매출 대시보드 리포트 화면', caption: '매출 대시보드 리포트' },
      { type: 'paragraph', text: '리포트는 위젯 배치를 담은 layout JSON으로 저장되고, 뷰어가 이를 피벗, 차트, KPI 카드 위젯으로 렌더링합니다. 차트는 Recharts 기반으로 막대, 라인, 영역, 파이, 도넛, 트리맵, 콤보 등 11종을 만들었습니다.' },
      { type: 'paragraph', text: '디자이너에서 만든 리포트가 뷰어에서 다르게 보이면 저작 도구는 신뢰를 잃습니다. 그래서 뷰어와 디자이너가 같은 렌더 컴포넌트를 공유하도록 설계해, 편집 화면이 곧 최종 화면이 되게 했습니다. 편집은 차원과 측정값을 캔버스로 끌어다 놓는 드래그앤드롭 방식이고, 1초 디바운스 자동 저장과 실행 취소(Ctrl+Z/Y)를 두어 저장 버튼을 신경 쓰지 않고 편집에 집중할 수 있게 했습니다.' },
      { type: 'heading', text: 'ERP 실데이터 연동' },
      { type: 'paragraph', text: '개발 초기에는 합성 데이터로 시작했지만, ERP DW의 매출, 프로젝트 원가, 노무 투입 데이터를 ETL로 적재해 실데이터 기반으로 전환했습니다. 영업 조직의 월별 매출 실적 대비 목표를 보여주는 매출 대시보드, 거래처 집중도나 손실 프로젝트 분석 같은 실제 분석 리포트를 이 위에서 만들었습니다.' },
      { type: 'heading', text: '자연어 데이터 조회' },
      { type: 'image', src: '/projects/bi/164.png', alt: 'AI 데이터 가져오기 화면', caption: '자연어 질문을 데이터셋과 차원, 측정값으로 해석해 리포트로 만들어 줍니다.' },
      { type: 'paragraph', text: '리포트를 직접 구성하지 않아도 되도록, 자연어 질문을 받아 알맞은 데이터셋과 차원, 측정값을 골라 조회하고 결과를 미리보기 표로 돌려주는 기능을 더했습니다. LLM은 등록된 데이터셋 메타 안에서 피벗 구성을 고르는 역할만 맡아, 조회가 정의된 범위를 벗어나지 않습니다. 만들어진 구성은 그대로 리포트 뷰어로 열어 저장할 수 있습니다.' },
      { type: 'image', src: '/projects/bi/165.png', alt: 'AI 데이터 가져오기 워크플로우 다이어그램', caption: '자연어 질문이 리포트가 되기까지 - LLM은 구성만 고르고, 조회와 검증은 기존 쿼리 엔진이 맡습니다.' },
      { type: 'heading', text: '인증과 권한, 운영' },
      { type: 'paragraph', text: '인증은 사내 SSO(OIDC)로 연동하고, 권한은 사번 기준으로 폴더, 데이터셋, 리포트 단위까지 내렸습니다. 관리자, 작성자, 조회자 등급에 따라 보이는 메뉴와 가능한 작업이 달라집니다.' },
      { type: 'paragraph', text: '운영 기능으로는 관리자 행위를 남기는 감사 로그, 감사 정리와 리포트 사전계산 스케줄 잡, 서버 오류의 메신저 알림을 두었고, DB 상태와 캐시 적중률을 확인하는 운영 모니터링 화면을 만들었습니다.' },
    ],
  },
  {
    slug: 'patent-management',
    title: '특허관리 시스템',
    category: 'Enterprise System',
    org: 'GlobalZeus',
    role: '1인 풀스택',
    period: '2022. 12 ~ 현재',
    tech: 'Next.js · Node.js · MSSQL',
    blocks: [
      { type: 'image', src: '/projects/patent-management/108.png', alt: '전사 특허 통계 대시보드', caption: '전사 특허 통계 대시보드 - 연도별 출원과 등록 추이, 분야별 분포' },
      { type: 'heading', text: '개요' },
      { type: 'paragraph', text: '개발 초창기이던 2022년에 EJS와 저장 프로시저 기반으로 구축해 운영해온 전사 특허와 직무발명 관리 시스템을, Next.js 구조로 현대화하고 있습니다. 출원과 등록 특허 현황, 직무발명 접수, 연차료 관리, 통계 대시보드에 더해 공지와 Q&A 게시판, 열람 권한을 관리하는 관리자 콘솔까지 하나의 앱으로 제공합니다.' },
      { type: 'paragraph', text: '2026년 들어 주요 화면을 App Router와 React Query, 별도 REST API 구조로 옮겼습니다. 기존 저장 프로시저와 데이터 계약은 그대로 두었습니다. 화면 이관에 그치지 않고 발명자 식별 체계를 사번 기준으로 정리하고 통계와 알림을 새로 설계하는 것까지를 현대화의 범위로 잡았습니다.' },
      { type: 'heading', text: '특허 현황 관리' },
      { type: 'image', src: '/projects/patent-management/109.png', alt: '특허 현황 목록 화면', caption: '특허 현황 목록 - 컬럼별 인라인 필터와 목록 다운로드' },
      { type: 'paragraph', text: '유효 특허와 만료 특허를 구분해 관리하고, 연차료(권리 유지비) 납부 기한을 알람일 기준으로 관리합니다. 기한을 놓치면 권리가 소멸되는 도메인이라, 데이터 정확성에 초점을 뒀습니다.' },
      { type: 'paragraph', text: '목록은 컬럼마다 인라인 필터를 두고, 자주 쓰는 검색 조건은 사용자별 프리셋으로 저장해 재사용합니다. 상세를 봤다가 목록으로 돌아오면 직전 목록 상태(필터·정렬)를 복원해 흐름이 끊기지 않게 했습니다. 현재 필터가 걸린 목록을 그대로 엑셀로 내려받을 수 있고, 발명자와 특허담당자는 조직도 프로필과 연결해 아바타로, 특허 등급(smart3)은 별도 컬럼으로 한 화면에서 확인합니다.' },
      { type: 'image', src: '/projects/patent-management/172.png', alt: '특허 상세(VIEW) 화면', caption: '특허 상세 - 출원 정보와 발명자, 기여도를 한 화면에서 확인합니다.' },
      { type: 'paragraph', text: '등록과 수정 폼은 양수도 등록, 발명에서 특허로의 전환, 분할출원(관리번호 자동 생성)까지 한 화면에서 다룹니다. 발명자 인적사항(주민등록번호, 주소, 기여도)을 입력할 때는 조직도와 최근 입력값에서 영문명·한자명과 이전 값을 제안해, 반복 입력의 수고를 줄였습니다.' },
      { type: 'image', src: '/projects/patent-management/110.png', alt: '직무발명 접수 현황 화면', caption: '직무발명 접수 현황 - 접수 상태와 사업 분야별 진행' },
      { type: 'paragraph', text: '직무발명 접수부터 특허 연결까지 이어지는 흐름을 한 화면에서 다룹니다.' },
      { type: 'image', src: '/projects/patent-management/173.png', alt: '직무발명 접수 상세(VIEW) 화면', caption: '직무발명 접수 상세 - 발명자와 기여도, 희망 출원 정보와 진행 상태를 한 화면에서 확인합니다.' },
      { type: 'heading', text: '통계 대시보드' },
      { type: 'paragraph', text: '요약 카드와 연도별 출원·등록 추이, 유효 특허의 분야별 분포, 발명자 순위, 등록 특허의 등급 분포를 한 화면에서 보여주고, 각 차트는 마우스를 올리면 세부 내역이 함께 뜹니다. 지재권 현황을 보고용 엑셀 없이 바로 확인하게 하는 것이 목적입니다.' },
      { type: 'heading', text: '게시판과 관리자 콘솔' },
      { type: 'image', src: '/projects/patent-management/168.png', alt: '관리자 콘솔 - 열람 권한 설정 화면', caption: '관리자 콘솔 - 화면별 열람 권한 설정' },
      { type: 'paragraph', text: '공지사항과 Q&A 게시판을 두어 특허 관련 공지와 문의를 앱 안에서 주고받고, 댓글과 첨부까지 지원합니다.' },
      { type: 'paragraph', text: '관리자 콘솔에서는 특허 현황, 직무발명, 게시판별로 열람할 사용자와 부서를 지정하고 등록·삭제 권한을 세분화합니다. 출원국, 출원인, 제품명, 특허법인 같은 코드 테이블도 화면에서 직접 관리해, 새 값이 생겨도 개발 없이 운영에서 추가합니다.' },
    ],
  },
  {
    slug: 'ai-platform',
    title: '사내 AI 플랫폼',
    category: 'AI Platform',
    org: 'GlobalZeus',
    role: '1인 풀스택',
    period: '2025. 12 ~ 현재',
    tech: 'Next.js · Node.js · FastAPI · LangGraph · Qdrant · Redis · MSSQL',
    blocks: [
      { type: 'image', src: '/projects/ai-platform/118.png', alt: '메인 화면', caption: '메인 화면' },
      { type: 'heading', text: '개요' },
      { type: 'paragraph', text: 'RAG(Retrieval-Augmented Generation) 기반 사내 챗봇으로 시작해, 지금은 웹 검색과 업무 데이터 조회, 코드 실행, 문서 생성까지 하나의 채팅에서 처리하는 사내 AI 플랫폼으로 발전시켰습니다.' },
      { type: 'paragraph', text: '문서를 올리면 파싱부터 임베딩, 저장까지 자동으로 처리되도록 데이터 파이프라인을 두었습니다. 사용자가 자료를 다시 정리하거나 새로 만들지 않고 있는 그대로 올려도, 파싱 단계에서 최대한 잘 처리해 그대로 지식으로 쌓이게 하고 싶었습니다.' },
      { type: 'image', src: '/projects/ai-platform/175.png', alt: '문서 처리 파이프라인 다이어그램', caption: '올린 문서가 지식이 되기까지 - 파싱하고 청킹해 임베딩한 뒤 벡터 DB에 저장하며, 전 과정이 백그라운드로 돌아갑니다.' },
      { type: 'paragraph', text: 'RAG 검색, 자유 질의, 웹 검색, 업무 데이터 조회를 종류별로 화면을 나누지 않고 하나의 채팅에서 모두 처리하도록 했습니다.' },
      { type: 'paragraph', text: '응답은 SSE 스트리밍에 Redis Stream 기반 재개 구조를 더해, 새로고침하거나 네트워크가 끊겨도 진행 중인 응답을 이어볼 수 있습니다. 반응형 UI라 모바일에서도 기능 제약 없이 쓸 수 있습니다.' },
      { type: 'heading', text: '아키텍처' },
      { type: 'image', src: '/projects/ai-platform/159.png', alt: 'AI 플랫폼 아키텍처 다이어그램', caption: '프론트엔드, BFF, AI 서버의 세 영역으로 나뉘고, 문서 생성과 코드 실행은 별도 샌드박스 컨테이너에서 격리 실행됩니다.' },
      { type: 'paragraph', text: 'Next.js 프론트엔드, Express BFF, Python/FastAPI AI 서버의 세 영역으로 분리해 각각 독립 서비스로 운영합니다. AI 서버는 LangGraph 워크플로우와 임베딩 파이프라인, LLM 호출을 책임지고, 문서 생성과 코드 실행은 다시 별도의 격리 샌드박스 컨테이너에서 코드로 실행됩니다.' },
      { type: 'paragraph', text: 'AI 서버 안에서 요청은 LangGraph 기반 에이전트 그래프로 처리됩니다. 진입 라우팅으로 경로를 정한 뒤 MainAgent가 도구를 반복해 호출하고, 지식 단독 질문과 웹페이지 생성은 전용 에이전트가 맡습니다.' },
      { type: 'image', src: '/projects/ai-platform/177.png', alt: 'AI 플랫폼 LangGraph 에이전트 그래프 다이어그램', caption: '실제 에이전트 그래프 - 분류 노드를 걷어낸 단일 ReAct 구조입니다. 진입 경로만 결정론으로 정하고, 이후 도구 선택은 에이전트가 판단합니다.' },
      { type: 'heading', text: '질의응답 인터페이스' },
      { type: 'subheading', text: '일반 질의' },
      { type: 'image', src: '/projects/ai-platform/119.png', alt: '일반 질의 화면', caption: '일반 질의 (텍스트와 이미지)' },
      { type: 'image', src: '/projects/ai-platform/02.png', alt: '파일 첨부 질의 화면', caption: '파일 첨부 질의' },
      { type: 'subheading', text: '프로젝트 (파일 + 지침)' },
      { type: 'image', src: '/projects/ai-platform/120.png', alt: '프로젝트 목록 화면', caption: '프로젝트 목록' },
      { type: 'image', src: '/projects/ai-platform/121.png', alt: '프로젝트 상세 화면 - 지침과 파일', caption: '프로젝트 지침과 파일' },
      { type: 'subheading', text: '웹 기반 검색' },
      { type: 'image', src: '/projects/ai-platform/122.png', alt: '웹 검색 화면', caption: '웹 검색 결과는 출처와 함께 답변에 표시됩니다.' },
      { type: 'image', src: '/projects/ai-platform/09.png', alt: '도구 사용 과정(trace) 화면', caption: '웹 검색 같은 도구 사용 과정을 단계별 타임라인(trace)으로 펼쳐 보여줍니다.' },
      { type: 'subheading', text: '사내 지식(RAG) 기반 검색' },
      { type: 'image', src: '/projects/ai-platform/123.png', alt: '사내 지식 검색 화면', caption: '사내 지식 검색은 어떤 문서에서 나온 답인지 출처를 보여줍니다.' },
      { type: 'image', src: '/projects/ai-platform/124.png', alt: '모델 선택 화면', caption: '모델 선택' },
      { type: 'paragraph', text: '사용자가 모드를 고르지 않아도 질문 성격에 맞는 경로로 흐르게 하는 것이 목표입니다. 처음에는 Supervisor 노드가 질문을 분류해 경로를 정했지만, 분류 노드를 걷어내고 에이전트가 스스로 도구를 고르는 단일 ReAct 구조로 옮겼습니다. 지금은 진입 경로만 결정론적으로 정하고(사내 지식과 프로젝트 파일은 미리 불러오도록), 그 뒤 RAG, 웹 검색, 코드 실행 같은 도구 선택은 에이전트가 판단합니다.' },      { type: 'paragraph', text: '사내 지식 검색은 한 번 찾고 끝내지 않습니다. 검색 계획 → 실행 → 평가로 이어지는 흐름에서 평가(critic) 노드가 결과의 충분성을 판단하고, 부족하면 범위를 넓혀 한 차례 보강 검색을 합니다.' },
      { type: 'image', src: '/projects/ai-platform/170.png', alt: '사내 지식(RAG) 검색 워크플로우 다이어그램', caption: '사내 지식 검색이 근거가 되기까지 - 계획하고 찾은 뒤, 충분하지 않으면 범위를 넓혀 한 차례 더 찾습니다.' },
      { type: 'paragraph', text: '첨부 파일은 종류에 따라 처리 경로가 다릅니다. 이미지와 PDF 페이지는 비전 모델이 읽고, csv, xlsx 같은 표 데이터는 LLM이 눈으로 읽다 틀리지 않도록 코드 실행 경로로 라우팅합니다.' },
      { type: 'paragraph', text: 'AI가 왜 이런 답을 내놨는지 보이지 않으면 신뢰가 쌓이지 않습니다. 에이전트가 어떤 도구를 어떤 순서로 썼는지 접었다 펼 수 있는 단계별 타임라인으로 보여주고(웹 검색, 사내 지식 검색, 분석·계산 등), 각 단계에 참고한 출처를 함께 답니다. 답변에는 인용 번호와 출처를 표시합니다.' },
      { type: 'heading', text: '자연어 업무 데이터 조회' },
      { type: 'image', src: '/projects/ai-platform/11.png', alt: '업무 데이터 질의 화면' },
      { type: 'image', src: '/projects/ai-platform/12.png', alt: '업무 데이터 응답 화면' },
      { type: 'paragraph', text: '자연어로 사내 업무 데이터를 조회하는 기능입니다. LLM이 SQL을 직접 생성하게 두는 대신, 검증된 내부 API와 조회 로직을 도구로 등록하고 LLM은 도구 선택과 파라미터 구성만 하도록 설계했습니다. 잘못된 쿼리가 실행될 여지를 구조적으로 차단하기 위해서입니다.' },
      { type: 'paragraph', text: '근태나 리조트 이용내역처럼 정형화된 도메인은 조회 함수를 도구로 등록하고, 사용자에게 해당 권한이 있을 때만 도구를 붙여 에이전트가 직접 호출하도록 했습니다. 문서 기반 검색(RAG)에 정형 데이터 조회까지 더해 플랫폼이 답할 수 있는 질문의 범위를 넓혔습니다.' },
      { type: 'heading', text: '사내 지식 관리' },
      { type: 'image', src: '/projects/ai-platform/125.png', alt: '사내 지식 챗봇 목록 화면', caption: '사내 지식 챗봇 목록' },
      { type: 'image', src: '/projects/ai-platform/126.png', alt: '대화 진입 화면', caption: '대화 진입 화면' },
      { type: 'image', src: '/projects/ai-platform/127.png', alt: '지식 생성 화면', caption: '생성 화면' },
      { type: 'image', src: '/projects/ai-platform/16.png', alt: '소스 등록 화면', caption: '소스 등록 화면' },
      { type: 'image', src: '/projects/ai-platform/17.png', alt: '권한 설정 화면', caption: '권한 설정 화면' },
      { type: 'paragraph', text: '사내 지식의 생성, 수정, 삭제와 권한 관리 화면입니다. 문서 전처리 → 임베딩 생성 → 벡터 DB(Qdrant) 저장으로 이어지는 파이프라인은 비동기 백그라운드 작업으로 돌아갑니다. 사용자는 업로드 직후 다른 일을 이어갈 수 있고, 파싱 결과는 상태 컬럼으로 추적됩니다.' },
      { type: 'paragraph', text: '접근 제어는 사번 기반 권한 모델로 임직원 단위까지 내렸습니다. 지식 대표 이미지는 따로 올리지 않아도 제목과 설명을 바탕으로 시각적으로 일관된 이미지가 자동 부여됩니다.' },
      { type: 'heading', text: '문서 생성' },
      { type: 'image', src: '/projects/ai-platform/128.png', alt: '문서 생성 화면 - 요청과 생성된 PPTX 파일', caption: '문서 생성 (PPTX)' },
      { type: 'image', src: '/projects/ai-platform/167.png', alt: '문서 뷰어 - 생성된 PPTX 슬라이드 미리보기', caption: '첨부된 파일을 열면 채팅 옆 뷰어에서 슬라이드를 페이지째 미리봅니다.' },
      { type: 'paragraph', text: '자연어 요청으로 docx, xlsx, pdf, pptx, txt, md 6종 문서를 만들어 채팅 메시지에 첨부합니다. 초기에는 문서 구조를 JSON으로 받아 렌더링했는데, 지금은 에이전트가 직접 코드를 작성해 격리 샌드박스에서 실행하고 파일을 만드는 방식으로 일원화했습니다. 답변과 파일 생성이 같은 대화 흐름에서 이어집니다.' },
      { type: 'paragraph', text: 'PPTX는 차트, 강조 패널, 카드 그리드 같은 블록을 조합해 슬라이드를 구성합니다. 생성 직후 좌표가 겹치거나 슬라이드 영역을 벗어난 요소를 규칙으로 검출해 바로잡습니다.' },
      { type: 'paragraph', text: '규칙 기반 검사가 못 잡는 시각 결함은 별도의 품질 검증 단계가 봅니다. 생성된 문서를 페이지 이미지로 렌더링해 멀티모달 모델이 텍스트 겹침이나 잘림 같은 결함을 판정하고, 결함이 발견되면 그 내용을 되먹여 문서를 다시 만들게 합니다. 재생성은 최대 두 번으로 제한해, 무한 반복 없이 결함 대부분을 걸러냅니다. 검수는 문서가 채팅에 첨부되기 전에 이뤄지므로, 결함이 있는 버전은 사용자에게 노출되지 않습니다.' },
      { type: 'image', src: '/projects/ai-platform/169.png', alt: '문서 생성 품질 검증 워크플로우 다이어그램', caption: '문서 요청이 파일이 되기까지 - 결함이 발견되면 결함 내역이 에이전트에게 돌아가 코드를 고쳐 다시 만듭니다.' },
      { type: 'paragraph', text: '백지 생성 외에, 사내에서 쓰는 pptx, xlsx, docx 양식을 업로드하면 원본 레이아웃을 보존한 채 값만 채워 넣는 양식 보존 경로도 따로 두었습니다. 실무 문서의 상당수는 새로 만드는 것이 아니라 정해진 양식을 채우는 일이기 때문입니다.' },
      { type: 'paragraph', text: '정적 문서 외에 인터랙티브 HTML(랜딩 페이지, 대시보드형 보고서)을 만드는 전용 에이전트 루프도 있습니다. 생성물은 채팅 옆 아티팩트 패널에서 바로 렌더링되고, 지금까지 만든 산출물은 라이브러리 화면에서 모아볼 수 있습니다.' },
      { type: 'image', src: '/projects/ai-platform/133.png', alt: '보관함 화면', caption: '채팅에서 쓰고 만든 파일은 보관함에 모입니다.' },
      { type: 'heading', text: '코드 인터프리터' },
      { type: 'image', src: '/projects/ai-platform/163.png', alt: '코드 인터프리터 차트 생성 화면', caption: '계산이나 시각화 요청은 코드를 작성해 실행하고, 결과를 인터랙티브 차트로 보여줍니다.' },
      { type: 'paragraph', text: '데이터 분석이나 차트 생성처럼 계산이 필요한 요청은 LLM이 직접 답하지 않고 Python 코드를 작성해 실행합니다. 실행 환경은 네트워크 차단, 읽기 전용 파일시스템, 리소스 제한을 건 격리 샌드박스를 별도 서비스로 두었고, 격리 항목을 자동 검증하는 스크립트를 배포 조건으로 삼았습니다.' },
      { type: 'paragraph', text: '결과 표와 차트는 브라우저에서 다시 그리는 인터랙티브 위젯으로 내려, 차트 종류를 바꾸거나 표로 전환할 수 있습니다.' },
      { type: 'image', src: '/projects/ai-platform/171.png', alt: '코드 인터프리터 표 전환 화면', caption: '같은 결과를 표로 전환한 화면 - 위젯의 차트 옵션에서 차트 종류를 바꾸거나 표로 볼 수 있습니다.' },
      { type: 'heading', text: '임시 채팅' },
      { type: 'image', src: '/projects/ai-platform/129.png', alt: '임시 채팅 화면', caption: '임시 채팅의 대화는 서버에 저장되지 않습니다.' },
      { type: 'paragraph', text: '사내 AI라도 사적이거나 민감한 질문을 할 수 있어야 실제로 쓰인다고 판단해 임시 채팅을 만들었습니다. 대화 본문은 서버에 저장하지 않고 브라우저 상태에만 두어, 새로고침이나 탭 종료와 함께 사라집니다.' },
      { type: 'paragraph', text: '다만 비용은 추적해야 하므로 사용 로그는 사번 없이 임시 플래그로만 남깁니다. 개인별 집계에서는 빠지고, 총 사용량과 비용 집계에는 잡히는 구조입니다.' },
      { type: 'heading', text: '사용자 메모리' },
      { type: 'paragraph', text: '같은 맥락을 대화마다 반복 설명하지 않도록, 대화에서 드러난 사용자 정보를 추출해 저장하고 이후 대화의 프롬프트에 주입합니다. 사용자가 직접 작성하는 커스텀 지침도 함께 지원합니다.' },
      { type: 'heading', text: '모델 사용 한도 제어' },
      { type: 'image', src: '/projects/ai-platform/130.png', alt: '한도 제어 화면', caption: '기본 한도 위에 사용자별 맞춤 한도를 얹을 수 있습니다.' },
      { type: 'paragraph', text: 'Claude Opus 같은 고단가 모델을 사내에 열면 예산 소진이 문제가 됩니다. 사용자별 월 USD 한도를 두고, 호출 단위 비용(모델 단가 × 사용 토큰)을 실시간으로 적재해 모델 선택 시점에 월 누적 비용을 검증합니다. 한도를 넘긴 모델은 자동으로 선택할 수 없게 됩니다.' },
      { type: 'paragraph', text: '모델은 OpenAI, Anthropic, Gemini를 함께 지원하고, 프로바이더별 API 차이는 드라이버 계층에서 흡수합니다. 프롬프트 캐싱의 캐시 토큰까지 분리 집계해 비용 계산이 실제 청구와 어긋나지 않게 했습니다.' },
      { type: 'heading', text: '대시보드' },
      { type: 'image', src: '/projects/ai-platform/131.png', alt: '관리자 대시보드 화면', caption: '관리자 대시보드' },
      { type: 'paragraph', text: '사용자별 사용량, 토큰 사용량, 모델별 비용, 지식별 활용 현황을 한 화면에서 봅니다. 운영과 비용 통제의 근거가 되는 화면입니다.' },
      { type: 'heading', text: '피드백' },
      { type: 'image', src: '/projects/ai-platform/24.png', alt: '피드백 전송 화면', caption: '피드백 전송 화면' },
      { type: 'image', src: '/projects/ai-platform/132.png', alt: '피드백 관리 화면', caption: '피드백 관리 화면' },
      { type: 'paragraph', text: 'AI 응답에 대한 사용자 피드백을 수집하고 관리자 페이지에서 확인합니다. 답변 품질을 개선할 지점을 찾는 채널입니다.' },
      { type: 'heading', text: '사내 발표' },
      { type: 'image', src: '/projects/ai-platform/174.png', alt: 'ZEUS AI DAY 발표 표지 - RAG 기술을 활용한 챗봇 소개', caption: '2026년 1월 사내 ZEUS AI DAY 발표 - RAG 기술을 활용한 챗봇 소개' },
      { type: 'paragraph', text: 'RAG 기반 사내 챗봇을 처음 구현한 뒤, 사내 개발자와 임직원을 대상으로 열린 ZEUS AI DAY에서 개발 경험을 발표했습니다. LLM과 RAG가 무엇인지부터, 사내에 도입하며 고민한 지점과 실제 서비스에 적용한 구조까지 정리해 공유했습니다.' },
      { type: 'image', src: '/projects/ai-platform/172.png', alt: 'RAG 동작 흐름 다이어그램 슬라이드', caption: 'RAG 동작 흐름 - 질문을 임베딩해 벡터 DB에서 유사 문서를 찾고, 그 근거로 답을 만듭니다.' },
      { type: 'image', src: '/projects/ai-platform/173.png', alt: 'RAG 서비스 구현 시 고려사항 슬라이드', caption: '구현하며 고른 스택 - 오케스트레이션(LangChain, LangGraph), 파싱과 임베딩, 벡터 DB(Qdrant), 화면(Next.js)' },
    ],
  },
  {
    slug: 'crm',
    title: '고객 관계 관리 시스템 (CRM)',
    category: 'Enterprise System',
    org: 'GlobalZeus',
    role: '1인 풀스택',
    period: '2025. 10 ~ 2025. 12',
    tech: 'Next.js · Node.js · MSSQL',
    blocks: [
      { type: 'image', src: '/projects/crm/26.png', alt: '대시보드 화면', caption: '대시보드 화면' },
      { type: 'heading', text: '개요' },
      { type: 'paragraph', text: '부서별로 엑셀, 메모, 개인 노트에 흩어져 있던 영업 정보를 한곳에 모으기 위한 사내 CRM을 구축했습니다. 전사 영업 현황을 한눈에 보는 것, 그리고 담당자가 바뀌어도 업무 연속성이 유지되는 것, 이 두 가지를 목표로 잡았습니다.' },
      { type: 'paragraph', text: '거래처, 담당자, 영업 프로젝트, 영업 활동 네 도메인을 공통 패널/모달 컴포넌트 기반의 같은 UX 패턴으로 통합했고, 외부 미팅과 출장이 잦은 영업 업무의 특성을 고려해 모바일 화면을 처음부터 함께 설계했습니다.' },
      { type: 'heading', text: '영업활동 캘린더' },
      { type: 'image', src: '/projects/crm/27.png', alt: '월간 캘린더 화면', caption: '월간 화면' },
      { type: 'image', src: '/projects/crm/28.png', alt: '주간 캘린더 화면', caption: '주간 화면' },
      { type: 'paragraph', text: '거래처별 영업활동을 캘린더로 시각화했습니다. 주간과 월간을 전환해 보며 영업 현황을 파악할 수 있습니다.' },
      { type: 'heading', text: '거래처 관리' },
      { type: 'subheading', text: '홈' },
      { type: 'image', src: '/projects/crm/29.png', alt: '거래처 홈 화면', caption: '홈 화면' },
      { type: 'subheading', text: '거래처 담당자' },
      { type: 'image', src: '/projects/crm/30.png', alt: '거래처 담당자 화면', caption: '거래처 담당자 화면' },
      { type: 'image', src: '/projects/crm/31.png', alt: '거래처 담당자 상세 조회 화면', caption: '거래처 담당자 상세 조회 화면' },
      { type: 'subheading', text: '영업 프로젝트' },
      { type: 'image', src: '/projects/crm/32.png', alt: '영업 프로젝트 화면', caption: '영업 프로젝트 화면' },
      { type: 'image', src: '/projects/crm/33.png', alt: '영업 프로젝트 상세 조회 화면', caption: '영업 프로젝트 상세 조회 화면' },
      { type: 'subheading', text: '영업 활동' },
      { type: 'image', src: '/projects/crm/34.png', alt: '영업활동 메뉴 화면', caption: '영업활동 메뉴' },
      { type: 'image', src: '/projects/crm/35.png', alt: '영업활동 상세 조회 화면', caption: '영업활동 상세 조회 화면' },
      { type: 'paragraph', text: '거래처 → 담당자 → 영업 프로젝트 → 영업 활동의 계층을 데이터 모델에서부터 분리했습니다. 한 거래처를 중심으로 모든 활동, 프로젝트, 담당자가 따라붙는 구조라, 담당자가 바뀌어도 거래처의 이력은 그대로 남습니다.' },
      { type: 'paragraph', text: '거래처 화면 안에서는 연관 정보가 페이지 이동 없이 패널로 열립니다. 영업 담당자가 거래처에서 시작해 담당자 → 프로젝트 → 과거 활동까지 한 흐름으로 따라가는 동선을 의도했습니다.' },
      { type: 'paragraph', text: '이를 위해 도메인별 상세 컴포넌트가 서로를 품을 수 있게 만들었습니다. 활동 상세 안에서 프로젝트를, 프로젝트 상세 안에서 담당자를 패널로 다시 여는 재귀적 드릴인 구조라, 어떤 화면에서 출발하든 같은 상세 컴포넌트가 재사용됩니다.' },
      { type: 'heading', text: 'ERP 연동' },
      { type: 'image', src: '/projects/crm/36.png', alt: '인사이트 화면', caption: '인사이트' },
      { type: 'image', src: '/projects/crm/37.png', alt: 'ERP 연동정보 화면', caption: 'ERP 연동정보' },
      { type: 'paragraph', text: 'ERP의 거래처 데이터를 연동해 매출, 견적, 품목, 장비, AS, 실적 현황을 조회하고, 사업부별, 연도별 매출 추이와 비중을 집계하는 인사이트 화면을 만들었습니다. 영업 정보와 회계 실적을 한 화면에서 보게 하려는 목적입니다.' },
      { type: 'heading', text: '협업과 개인화' },
      { type: 'paragraph', text: '프로젝트와 활동에는 댓글과 파일 첨부가 붙고, 주요 이벤트는 알림으로 발송됩니다. CRM 활동을 PMS의 보드와 보고에 연결하는 연동도 있어서, 영업 활동이 프로젝트 업무로 이어지는 흐름을 시스템 간에 끊지 않습니다.' },
      { type: 'paragraph', text: '자주 보는 거래처는 즐겨찾기와 최근 방문 목록으로 바로 접근하고, 목록의 컬럼 구성은 사용자별로 저장됩니다. 명함 관리 서비스(리멤버)에서 담당자를 일괄로 가져오는 기능도 두어, 초기 데이터 입력의 벽을 낮췄습니다.' },
      { type: 'heading', text: '모바일' },
      { type: 'image', src: '/projects/crm/38.png', alt: '모바일 홈 화면' },
      { type: 'image', src: '/projects/crm/39.png', alt: '모바일 거래처 화면' },
      { type: 'image', src: '/projects/crm/40.png', alt: '모바일 영업활동 화면' },
      { type: 'image', src: '/projects/crm/41.png', alt: '모바일 상세 화면' },
      { type: 'image', src: '/projects/crm/42.png', alt: '모바일 캘린더 화면' },
      { type: 'paragraph', text: '반응형 대신 디바이스별 화면 분리를 택했습니다. 영업 업무에서 모바일은 보조가 아니라 주력이 되는 순간이 많아서, PC 화면을 줄여 보여주는 정도로는 부족하고, 모바일에서도 모든 기능이 동일하게 돌아가야 했기 때문입니다.' },
    ],
  },
  {
    slug: 'pms',
    title: '프로젝트 관리 시스템 (PMS)',
    category: 'Enterprise System',
    org: 'GlobalZeus',
    role: '2인 개발(풀스택)',
    period: '2023. 4 ~ 2025. 7',
    tech: 'Node.js · EJS · React(Next.js) · MSSQL · Redis · Elasticsearch · Socket.IO · ONLYOFFICE',
    blocks: [
      { type: 'image', src: '/projects/pms/58.png', alt: 'WBS (일정관리) 화면', caption: 'WBS (일정관리) 화면' },
      { type: 'heading', text: '개요' },
      { type: 'paragraph', text: '부서마다 제각각의 양식과 도구로 관리되던 사내 프로젝트를 단일 표준 체계로 통합하는 시스템입니다.' },
      { type: 'paragraph', text: 'WBS, 보드, 업무노트, 보고, 산출물, 이슈가 한 프로젝트 화면 안에 모이도록 설계해 여러 도구로 정보가 분산되는 문제를 해소했습니다. 일반 프로젝트와 ERP 연동 프로젝트를 같은 구조 위에서 처리하도록 해서, 새 프로젝트 유형이 생겨도 메뉴 구조를 바꾸지 않고 확장할 수 있습니다.' },
      { type: 'paragraph', text: '1차 기본 시스템(2023. 4 ~ 8), 2차 ERP 연동(2024. 1 ~ 3), 3차 통합검색과 전반 개선(2025. 5 ~ 7)으로 단계를 나눠 개발했고, 2026년에는 프로젝트 요약 탭과 협업문서(실시간 공동 편집) 기능을 더했습니다.' },
      { type: 'heading', text: '홈 화면' },
      { type: 'image', src: '/projects/pms/59.png', alt: '홈 대시보드 화면' },
      { type: 'paragraph', text: '사용자 기준의 업무 진행 현황을 모은 개인 대시보드입니다. 프로젝트 목록과 주요 정보를 보여주고, 클릭하면 해당 화면으로 바로 이동합니다.' },
      { type: 'heading', text: '프로젝트 대시보드' },
      { type: 'image', src: '/projects/pms/60.png', alt: '프로젝트 대시보드 화면' },
      { type: 'paragraph', text: 'WBS 진척 기반 요약 대시보드는 완료, 진행, 임박, 지연 상태와 담당자별 분포를 한눈에 보여주고, 지연과 임박 항목을 강조해 문제가 커지기 전에 발견할 수 있게 했습니다. ERP 연동 프로젝트는 별도 화면에서 원가, 공수, 작업일수를 계획 대비 실적으로 비교합니다.' },
      { type: 'heading', text: '프로젝트 메뉴' },
      { type: 'subheading', text: '요약' },
      { type: 'image', src: '/projects/pms/138.png', alt: '프로젝트 요약 탭 화면', caption: '요약 탭' },
      { type: 'paragraph', text: '프로젝트에 들어가면 가장 먼저 만나는 화면입니다. 보드, 보고, 업무노트, 산출물 건수와 최근 7일의 증감, WBS와 보드의 진행 현황, 담당자별 분포를 한 화면에 모았습니다. 세부 메뉴를 돌아다니지 않아도 어디가 지연되고 있는지부터 눈에 들어오게 하려는 의도입니다.' },
      { type: 'subheading', text: 'WBS (일정관리)' },
      { type: 'image', src: '/projects/pms/61.png', alt: 'WBS 메뉴 화면', caption: 'WBS 메뉴 화면' },
      { type: 'image', src: '/projects/pms/62.png', alt: 'WBS 상세정보 화면', caption: '상세정보 화면' },
      { type: 'paragraph', text: '작업을 트리 구조로 관리하고 Gantt 차트로 일정을 시각화합니다. 상위/하위 작업의 일정 의존성을 데이터 모델 차원에서 표현해, 상위 일정이 바뀌면 그 영향이 하위로 자연스럽게 전파됩니다.' },
      { type: 'paragraph', text: '상세 정보는 페이지 이동 대신 패널로 열립니다. 일정을 보다가 작업 하나를 수정하는 흐름이 끊기지 않게 하기 위한 선택입니다. 변경 이력 관리도 이 패널에서 함께 처리합니다.' },
      { type: 'subheading', text: '업무노트' },
      { type: 'image', src: '/projects/pms/63.png', alt: '업무노트 화면', caption: '업무노트 화면' },
      { type: 'image', src: '/projects/pms/64.png', alt: '업무노트 버전 관리 화면', caption: '버전 관리 화면' },
      { type: 'paragraph', text: '프로젝트 단위의 메모입니다. 입력하는 즉시 자동 저장되어 데이터 유실을 막고, Redis 기반 편집 잠금과 Socket.IO 프레즌스(누가 편집 중인지 실시간 표시)로 동시 수정 충돌을 방지했습니다. 버전 스냅샷이 주기적으로 자동 누적되고, 이전 버전으로 복원할 때는 현재 상태를 백업 버전으로 먼저 남기는 비파괴 방식입니다.' },
      { type: 'subheading', text: '보고' },
      { type: 'image', src: '/projects/pms/65.png', alt: '보고 생성 화면', caption: '보고 생성 화면' },
      { type: 'image', src: '/projects/pms/66.png', alt: '보고 목록 화면', caption: '보고 목록 화면' },
      { type: 'image', src: '/projects/pms/67.png', alt: '정기보고 화면', caption: '정기보고 화면' },
      { type: 'paragraph', text: '수시 보고와 정기 보고를 분리했습니다. 정기 보고는 시리즈 단위로 반복 규칙(매주, 매월 n번째 요일 등)을 정의하면 회차가 규칙에 따라 미리 생성되고, 보고자가 지정되거나 보고가 제출되는 시점에 알림이 갑니다. 회차를 매번 사람이 만들지 않아도 이어지게 한 설계입니다. 작성 중인 보고는 임시저장 상태로 두면 검색과 알림에서 제외되고, 게시하는 순간에만 공유됩니다.' },
      { type: 'subheading', text: '산출물' },
      { type: 'image', src: '/projects/pms/68.png', alt: '산출물 목록 화면', caption: '산출물 목록 화면' },
      { type: 'image', src: '/projects/pms/69.png', alt: '산출물 상세 화면', caption: '상세 화면' },
      { type: 'paragraph', text: '산출물을 버전과 변경 이력으로 관리합니다. 어느 시점에 어떤 산출물이 만들어졌는지 추적할 수 있습니다.' },
      { type: 'heading', text: '통합검색' },
      { type: 'image', src: '/projects/pms/70.png', alt: '통합검색 화면', caption: '통합검색 화면' },
      { type: 'image', src: '/projects/pms/71.png', alt: '검색이력 조회 화면', caption: '검색이력 조회' },
      { type: 'image', src: '/projects/pms/72.png', alt: '첨부파일 조회 화면', caption: '첨부파일 조회' },
      { type: 'paragraph', text: 'Elasticsearch 기반으로 보고, 업무노트, 게시판, 산출물, 댓글, 첨부파일까지 하나의 인덱스로 묶었습니다. 프로젝트가 쌓일수록 "그 내용이 어디 있었지"를 찾는 비용이 커지는 문제에 대한 답입니다. 색인은 본 동작을 막지 않는 비동기로 처리하고, 문서 권한이 바뀌면 재색인해 검색 결과에서도 열람 권한이 지켜집니다. 검색 키워드 하이라이트와 최근 검색어 저장도 함께 구현했습니다.' },
      { type: 'heading', text: '협업문서 (실시간 공동 편집)' },
      { type: 'image', src: '/projects/pms/139.png', alt: '협업 문서 목록 화면', caption: '협업 탭 - 문서 목록' },
      { type: 'image', src: '/projects/pms/140.png', alt: '협업 문서 공동 편집 화면', caption: '브라우저 안에서 열리는 공동 편집기' },
      { type: 'paragraph', text: '프로젝트 안에서 엑셀, 워드, PPT를 브라우저로 함께 편집하는 협업 탭을 만들었습니다. ONLYOFFICE Document Server를 사내에 직접 띄워 임베드했고, 같은 문서를 여러 명이 동시에 편집하며 참여자가 실시간으로 표시됩니다.' },
      { type: 'paragraph', text: '편집 세션이 끝날 때마다 버전 스냅샷이 자동으로 쌓입니다. 이전 버전은 읽기 전용으로 미리 보고, 복원하면 그 내용으로 되돌리되 기존 버전 이력은 그대로 남습니다. 각 버전에는 공동 편집에 참여한 사람이 함께 기록됩니다.' },
      { type: 'paragraph', text: '문서는 공개와 비공개로 나뉘고, 비공개 문서는 권한을 받은 사람만 보거나 편집할 수 있습니다. 읽기 전용 사용자에게는 저장 콜백 자체를 발급하지 않아 서버 차원에서 수정이 차단됩니다. 세션이 없는 문서 서버의 호출은 문서별 토큰으로 검증합니다.' },
      { type: 'paragraph', text: '협업 문서의 본문 텍스트도 추출해 통합검색에 색인했습니다. 색인에 문서 권한까지 반영해, 검색 결과에서도 비공개가 그대로 지켜집니다.' },
    ],
  },
  {
    slug: 'visit-reservation',
    title: '방문 예약 시스템',
    category: 'Enterprise System',
    org: 'GlobalZeus',
    role: '1인 풀스택',
    period: '2025. 3 ~ 2025. 5',
    tech: 'Next.js · Node.js · MSSQL · Redis · Socket.IO',
    blocks: [
      { type: 'image', src: '/projects/visit-reservation/49.png', alt: '방문 예약 시스템 메인 화면' },
      { type: 'heading', text: '개요' },
      { type: 'paragraph', text: '임직원 승인 절차를 기반으로 한 방문 예약과 출입 관리 시스템을 구축했습니다. 승인이 완료되면 QR 출입증 발급과 경비실 확인까지 이어지도록 프로세스를 자동화했고, PC와 모바일을 모두 지원하는 반응형 웹으로 만들었습니다.' },
      { type: 'heading', text: '가입 / 인증' },
      { type: 'image', src: '/projects/visit-reservation/50.png', alt: '회원가입 화면' },
      { type: 'paragraph', text: '회원가입은 NICE 본인인증 API 기반 휴대폰 인증으로 처리합니다. 해외 방문객처럼 휴대폰 인증이 어려운 사용자가 있어서, 임직원 승인 기반의 가입 경로를 따로 설계했습니다.' },
      { type: 'paragraph', text: '인증은 Access Token / Refresh Token 구조의 JWT로 구현하고, Refresh Token은 Redis에 보관해 갱신과 무효화를 다룹니다. 백오피스로 들어오는 임직원은 사내 SSO(Brity OIDC)로 로그인하며, 로그인 후 돌아갈 주소는 사내 도메인만 허용해 오픈 리다이렉트를 막았습니다.' },
      { type: 'heading', text: '방문 신청' },
      { type: 'image', src: '/projects/visit-reservation/51.png', alt: '방문 신청 화면', caption: '방문 신청 화면' },
      { type: 'image', src: '/projects/visit-reservation/52.png', alt: '교육 및 서약 화면', caption: '교육 및 서약 화면' },
      { type: 'image', src: '/projects/visit-reservation/53.png', alt: '교육 및 서약 화면', caption: '교육 및 서약 화면' },
      { type: 'paragraph', text: '방문 유형(일반 미팅, 협력사 작업, 외부 점검 등)에 따라 필요한 교육과 서약이 다릅니다. 유형을 고르면 교육 콘텐츠와 서약 항목이 자동으로 바뀌도록 설계해, 신청 → 교육 수강 → 서약 동의 → 임직원 승인으로 이어지는 단계별 흐름을 만들었습니다.' },
      { type: 'paragraph', text: '회원 신청 외에 비회원(게스트) 신청 경로를 따로 두었고, 방문 시 반입하는 저장매체 등록과 게스트 Wi-Fi 안내까지 신청 흐름 안에서 처리됩니다.' },
      { type: 'heading', text: '백오피스' },
      { type: 'subheading', text: '임직원 승인 화면' },
      { type: 'image', src: '/projects/visit-reservation/54.png', alt: '임직원 승인 화면' },
      { type: 'paragraph', text: '임직원이 본인에게 온 방문 신청을 확인하고 승인/반려하는 화면입니다. 승인자에게는 본인 담당 건만, 관리자에게는 전체 건이 보이는 두 단계 권한 모델을 적용했고, 자리에 없어도 처리할 수 있도록 모바일 화면을 분리했습니다.' },
      { type: 'paragraph', text: '승인 결과는 Socket.IO로 브로드캐스트되어, 열려 있는 키오스크와 백오피스 화면이 새로고침 없이 실시간으로 갱신됩니다.' },
      { type: 'subheading', text: '관리자 화면' },
      { type: 'image', src: '/projects/visit-reservation/55.png', alt: '관리자 설정 화면' },
      { type: 'image', src: '/projects/visit-reservation/56.png', alt: '교육 콘텐츠 관리 화면' },
      { type: 'paragraph', text: '방문 유형과 교육 콘텐츠는 관리자가 직접 관리합니다. 새 방문 유형이 생겨도 개발 없이 운영에서 추가할 수 있습니다. 교육과 서약은 콘텐츠 관리에 더해 방문객별 이수 현황을 조회하고 엑셀로 내려받을 수 있게 해, 이수 여부를 운영에서 추적합니다.' },
      { type: 'heading', text: '출입 관리' },
      { type: 'image', src: '/projects/visit-reservation/57.png', alt: '출입 관리 화면' },
      { type: 'paragraph', text: '승인이 완료된 방문객에게는 QR 출입증이 발급됩니다. 실물 방문 카드는 방문 유형별로 등록해두고 키오스크에서 배정하고 회수하는 방식으로 관리합니다.' },
      { type: 'paragraph', text: '경비실과 키오스크 환경에서 방문 현황과 QR 확인, 카드 배포와 회수 상태를 실시간으로 확인하는 화면을 만들었습니다.' },
    ],
  },
  {
    slug: 'attendance',
    title: '근태현황 및 이상치 소명 시스템',
    category: 'Enterprise System',
    org: 'GlobalZeus',
    role: '1인 풀스택',
    period: '2025. 1 ~ 2025. 3',
    tech: 'Node.js · EJS · MSSQL',
    blocks: [
      { type: 'image', src: '/projects/attendance/43.png', alt: '근태현황 시스템 메인 화면' },
      { type: 'heading', text: '개요' },
      { type: 'paragraph', text: '선택적 근로제가 도입되면서, 자유로워진 근무 환경에서 생기는 누락이나 이상 근무 데이터를 관리할 시스템이 필요해져 구축했습니다.' },
      { type: 'paragraph', text: '여기서는 확인의 방향을 뒤집었습니다. 관리자가 이상 데이터를 일일이 찾아 확인하는 대신, 이상치가 잡히면 당사자에게 소명 요청이 가고 임직원이 스스로 확인해 소명하면 부서장에게 자동으로 전달되는 흐름(셀프 소명 → 자동 통지)으로 만들었습니다.' },
      { type: 'heading', text: '근태 대시보드' },
      { type: 'image', src: '/projects/attendance/115.png', alt: '이상치 근무 현황 대시보드', caption: '이상치 근무 현황 대시보드' },
      { type: 'image', src: '/projects/attendance/45.png', alt: '대시보드 상세보기 화면', caption: '상세보기 화면' },
      { type: 'paragraph', text: '근무 데이터에서 무엇을 이상치로 볼 것인지부터 정의했습니다. 출근 누락, 중복 퇴근, 지각과 조퇴, 월 소정근로 미달 등 7가지 유형을 규칙으로 만들고, 유형별 발생 빈도와 추이를 차트로 시각화해 조직의 근태 상태를 한눈에 파악할 수 있습니다.' },
      { type: 'heading', text: '근무현황 조회' },
      { type: 'image', src: '/projects/attendance/46.png', alt: '근무현황 조회 화면' },
      { type: 'paragraph', text: '실시간 근무 데이터와 근무 신청 내역을 합쳐 구성원별 근무 상태를 확인하는 화면입니다.' },
      { type: 'heading', text: '이상치 소명 관리' },
      { type: 'image', src: '/projects/attendance/47.png', alt: '이상치 목록 화면', caption: '이상치 목록' },
      { type: 'image', src: '/projects/attendance/48.png', alt: '근무 보고서 화면', caption: '근무 보고서' },
      { type: 'paragraph', text: '일 단위로 발생하는 이상치를 임직원 본인이 확인하고 소명합니다. 소명 요청과 제출 결과는 메일, 사내 메신저, 인앱 벨 멀티 채널 알림으로 당사자와 부서장에게 전달되고, 소명이 불필요한 케이스는 예외 규칙으로 걸러냅니다. 관리자가 개입할 일을 최소화하는 것이 목표였습니다.' },
    ],
  },
  {
    slug: 'hr-evaluation',
    title: '인사평가 시스템',
    category: 'Enterprise System',
    org: 'GlobalZeus',
    role: '2인 개발(풀스택)',
    period: '2023. 10 ~ 2024. 12',
    tech: 'Node.js · EJS · MSSQL',
    blocks: [
      { type: 'image', src: '/projects/hr-evaluation/73.png', alt: '인사평가 시스템 메인 화면' },
      { type: 'heading', text: '개요' },
      { type: 'paragraph', text: '기존 SaaS형 평가 시스템의 한계를 대체하기 위한 사내 맞춤형 평가 시스템입니다.' },
      { type: 'paragraph', text: '목표 기반 성과 관리 체계를 설계하고 이를 반영한 평가 프로세스 전반을 구현했습니다. 1차 목표와 성과관리(2023. 10 ~ 12), 2차 평가(2024. 10 ~ 12)로 나눠 개발했습니다.' },
      { type: 'heading', text: '목표관리' },
      { type: 'image', src: '/projects/hr-evaluation/116.png', alt: '목표 보드 화면', caption: '목표 보드' },
      { type: 'image', src: '/projects/hr-evaluation/74.png', alt: '목표 목록 화면', caption: '목표 목록' },
      { type: 'image', src: '/projects/hr-evaluation/75.png', alt: '목표 승인 관리 화면', caption: '목표 승인 관리 화면' },
      { type: 'image', src: '/projects/hr-evaluation/76.png', alt: '목표 상세 화면', caption: '목표 상세 화면' },
      { type: 'paragraph', text: '목표는 사업부 → 그룹 → 팀 → 개인으로 연결되는 트리 구조입니다. 개인 목표가 상위 조직의 어떤 목표에 기여하는지 따라갈 수 있고, 목표에는 승인 결재와 파일 첨부와 댓글이 붙습니다.' },
      { type: 'paragraph', text: '목표 입력과 수정은 패널 기반 상세 화면에서 처리하고, 목표별 성과 정보와 변경 이력은 자동으로 누적됩니다. 평가 시점에 이 목표가 언제 어떻게 조정됐는지를 객관적 근거로 남기기 위한 설계입니다.' },
      { type: 'heading', text: '평가진행' },
      { type: 'image', src: '/projects/hr-evaluation/77.png', alt: '평가 메인 화면', caption: '평가 메인 화면' },
      { type: 'image', src: '/projects/hr-evaluation/78.png', alt: '업적평가 진행 화면', caption: '업적평가 진행 화면' },
      { type: 'image', src: '/projects/hr-evaluation/79.png', alt: '평가정보 확인 화면', caption: '평가정보 확인 화면' },
      { type: 'image', src: '/projects/hr-evaluation/80.png', alt: '종합평가 진행 화면', caption: '종합평가 진행 화면' },
      { type: 'image', src: '/projects/hr-evaluation/81.png', alt: '평가결과 조회 화면', caption: '평가결과 조회 화면' },
      { type: 'paragraph', text: '평가자, 피평가자, 검토자, 관리자까지 같은 사람이 여러 역할을 갖는 시스템입니다. 평가받는 화면과 평가하는 화면, 부서원 결과 확인 화면을 한 진입점에서 자연스럽게 전환하도록 설계했습니다.' },
      { type: 'paragraph', text: '평가 시즌에 지금 무엇을 해야 하는지 헤매지 않도록, 진행 상태(미시작, 진행중, 검토대기, 확정)를 한 화면에 모아 보여줍니다.' },
      { type: 'paragraph', text: '점수는 업적 평가와 역량 평가의 가중치 기반으로 자동 산출됩니다. 등급은 S~D 비율과 점수 예산이 정해진 상대평가 방식인데, 평가자가 예산 안에서 배정하되 비율 초과나 점수-순위 역전 같은 규칙 위반은 시스템이 막습니다. 산식과 규칙을 시스템이 강제해 평가의 일관성을 확보했습니다.' },
      { type: 'paragraph', text: '평가 입력 → 1차 평가 → 2차 평가(검토) → 결과 확정 → 피드백 공개까지 전체 흐름을 설계하고 구현했습니다.' },
    ],
  },
];
