import type { Build } from './types';

export const builds: Build[] = [
  {
    slug: 'ai-platform',
    title: '사내 AI 플랫폼 (RAG 챗봇)',
    category: 'AI Platform',
    org: 'GlobalZeus',
    period: '2025', // TODO: 정확한 수행 기간 확인
    tech: 'Next.js · Node.js · FastAPI · LangGraph · Qdrant · Redis · MSSQL',
    blocks: [
      { type: 'heading', text: '주요 내용' },
      { type: 'paragraph', text: 'RAG(Retrieval-Augmented Generation) 기반 사내 챗봇 AI 플랫폼을 설계 및 개발했습니다.' },
      { type: 'paragraph', text: '문서 업로드 시 파싱·청킹·임베딩·벡터 DB 저장까지 자동화된 데이터 파이프라인을 구축했습니다.' },
      { type: 'paragraph', text: '일반 질의, 사내 문서 검색, 프로젝트 파일 검색, 웹 검색, 사내 업무 데이터 조회를 통합한 멀티 소스 질의 처리 구조를 설계했습니다.' },
      { type: 'paragraph', text: 'LangGraph 기반 상태형 LLM 워크플로우(Agent Flow)로 질의 유형에 따른 분기와 응답 흐름을 구현했습니다.' },
      { type: 'paragraph', text: '자연어 요청으로 docx·xlsx·pdf·pptx 등 6종 포맷 문서를 자동 생성해 채팅 메시지에 첨부하는 기능을 구현했습니다.' },
      { type: 'paragraph', text: 'SSE 기반 실시간 스트리밍 응답과 Redis Stream 기반 응답 재개 구조를 적용해, 새로고침이나 네트워크 단절 시에도 진행 중인 응답을 이어볼 수 있도록 했습니다.' },
      { type: 'heading', text: '주요 성과' },
      { type: 'paragraph', text: '프론트엔드·백엔드·RAG 서버를 연계해 문서 등록부터 검색, 응답 생성, 문서 생성까지 하나의 서비스 흐름으로 통합했습니다.' },
      { type: 'paragraph', text: '관리자 대시보드로 사용자별 사용량, 토큰 사용량, 모델별 비용, 지식별 활용 현황을 통합 확인할 수 있도록 구현했습니다.' },
      { type: 'paragraph', text: '사용자별 한도와 과금 모델 사용 제한 정책을 반영해 비용 통제·운영 관리 기반을 강화했습니다.' },
    ],
  },
  {
    slug: 'work-app-platform',
    title: '업무 앱 제작 플랫폼',
    category: 'No-Code Platform',
    org: 'GlobalZeus',
    period: '2026',
    tech: 'Next.js · Node.js · MSSQL · Redis · Socket.IO',
    blocks: [
      { type: 'heading', text: '주요 내용' },
      { type: 'paragraph', text: '그룹웨어 전환 과정에서 다우오피스 Works를 대체하기 위한 노코드 기반 사내 협업 플랫폼을 1인 풀스택으로 구축했습니다.' },
      { type: 'paragraph', text: '코드 없이 입력 양식을 설계하는 폼 빌더와, 필드 단위로 외부 DB SELECT 쿼리를 연동하는 데이터 연동 기능을 구현했습니다.' },
      { type: 'paragraph', text: '목록을 테이블·보드(칸반)로 전환하고 게이지·막대·라인·카드 차트로 시각화하는 화면을 구현했습니다.' },
      { type: 'paragraph', text: '상태 머신(워크플로우) 기반 프로세스 관리와, 저장 시 정합성 오류를 서버에서 검증하는 방어 로직을 구성했습니다.' },
      { type: 'paragraph', text: '공유 범위·역할 기반 권한·문서/앱 단위 비공개를 조합한 접근 제어를 구현했습니다.' },
      { type: 'heading', text: '주요 성과' },
      { type: 'paragraph', text: '앱 간 데이터 참조, CSV 일괄 등록(백그라운드 워커), 비동기 큐 기반 다운로드 등 운영 기능을 통합했습니다.' },
      { type: 'paragraph', text: '앱별 API Key 발급으로 외부 시스템과 연동하고, 사내 표준 결재 시스템과의 연동까지 지원해 노코드 앱을 실제 업무 흐름에 연결했습니다.' },
    ],
  },
  {
    slug: 'pms',
    title: '프로젝트 관리 시스템 (PMS)',
    category: 'Enterprise System',
    org: 'GlobalZeus',
    period: '2023 — 2025',
    tech: 'Next.js · Node.js · MSSQL · Elasticsearch · Socket.IO',
    blocks: [
      { type: 'heading', text: '주요 내용' },
      { type: 'paragraph', text: 'PMS 전반 아키텍처를 설계하고, WBS 기반 프로젝트 구조를 중심으로 보고·업무노트·산출물 관리 기능을 구현했습니다.' },
      { type: 'paragraph', text: 'ERP 연동 프로젝트 생성·관리 기능과 대시보드·설계정보·원가정보·공수정보 조회 기능을 개발했습니다.' },
      { type: 'paragraph', text: 'Elasticsearch 기반 통합 검색(보고·업무노트·댓글·첨부)을 설계·구현했습니다.' },
      { type: 'paragraph', text: 'Socket.IO를 활용한 메모 동시 작성 제어·편집 상태 표시·이탈 처리 기능을 구현했습니다.' },
      { type: 'heading', text: '주요 성과' },
      { type: 'paragraph', text: 'WBS 기반 보고·업무노트·산출물 관리를 중심으로 프로젝트 수행 이력을 체계적으로 관리할 수 있는 구조를 구현했습니다.' },
      { type: 'paragraph', text: 'ERP 연동으로 설계·원가·공수 정보를 통합 조회하고, 통합 검색과 정기 보고 자동화로 운영 편의를 높였습니다.' },
    ],
  },
  {
    slug: 'crm',
    title: '고객 관계 관리 시스템 (CRM)',
    category: 'Enterprise System',
    org: 'GlobalZeus',
    period: '2024', // TODO: 정확한 수행 기간 확인
    tech: 'Next.js · Node.js · MSSQL',
    blocks: [
      { type: 'heading', text: '주요 내용' },
      { type: 'paragraph', text: '거래처·담당자·영업 프로젝트·영업 활동 중심의 CRM 시스템 화면과 기능을 설계하고 구현했습니다.' },
      { type: 'paragraph', text: '거래처 정보·담당자 그룹·영업 프로젝트·활동 이력을 공통으로 확인할 수 있는 재사용 가능한 UI 컴포넌트 구조를 설계했습니다.' },
      { type: 'paragraph', text: '거래처별 영업 활동과 구성원 일정을 월간·주간 캘린더로 시각화했습니다.' },
      { type: 'paragraph', text: 'ERP 데이터 연동으로 거래처별 매출·견적·품목·장비·AS·실적 현황을 조회할 수 있는 기능을 개발했습니다.' },
      { type: 'heading', text: '주요 성과' },
      { type: 'paragraph', text: '거래처·담당자·프로젝트·활동을 하나의 흐름으로 연결해 데이터 관리 일관성을 높였습니다.' },
      { type: 'paragraph', text: '공통 리스트·상세 패널·태스크바 등 재사용 화면 구조를 적용해 기능 확장과 유지보수 효율을 개선했습니다.' },
    ],
  },
  {
    slug: 'hr-evaluation',
    title: '인사평가 시스템',
    category: 'Enterprise System',
    org: 'GlobalZeus',
    period: '2023 — 2024',
    tech: 'Next.js · Node.js · MSSQL',
    blocks: [
      { type: 'heading', text: '주요 내용' },
      { type: 'paragraph', text: '목표 기반 인사평가 체계의 시스템 구조를 설계하고 UI/UX를 기획·구현했습니다.' },
      { type: 'paragraph', text: '사업부·그룹·팀·개인 단위로 연결되는 계층형 목표 설정 및 성과 관리 화면을 설계·개발했습니다.' },
      { type: 'paragraph', text: '목표별 최종 성과 입력과 가중치 반영 자동 점수 산정 로직을 구현했습니다.' },
      { type: 'paragraph', text: '부서별 상대평가·절대평가를 구분한 종합평가와 평가 등급 자동 부여 기능을 개발했습니다.' },
      { type: 'heading', text: '주요 성과' },
      { type: 'paragraph', text: '목표 설정부터 성과 관리·업적평가·역량평가·종합평가·등급 부여까지 이어지는 인사평가 프로세스를 시스템화했습니다.' },
      { type: 'paragraph', text: '목표별 가중치 반영 자동 점수 산정으로 평가 산식의 일관성과 운영 효율을 높였습니다.' },
    ],
  },
  {
    slug: 'visit-reservation',
    title: '방문 예약 시스템',
    category: 'Enterprise System',
    org: 'GlobalZeus',
    period: '2024', // TODO: 정확한 수행 기간 확인
    tech: 'Next.js · Node.js · MSSQL',
    blocks: [
      { type: 'heading', text: '주요 내용' },
      { type: 'paragraph', text: '임직원 승인 절차 기반의 출입 관리를 위해 방문예약 시스템 화면과 기능을 설계하고 개발했습니다.' },
      { type: 'paragraph', text: '신청 유형에 따라 교육 이수·서약서 작성·QR 코드 발급으로 이어지는 프로세스를 구현했습니다.' },
      { type: 'paragraph', text: '임직원 신청자와 비회원 방문객을 구분해 각각의 신청·조회·처리 흐름을 반영했습니다.' },
      { type: 'paragraph', text: '경비실·키오스크 환경에서 방문 현황·QR 확인·카드 배포 및 회수 상태를 관리하는 화면을 개발했습니다.' },
      { type: 'heading', text: '주요 성과' },
      { type: 'paragraph', text: '방문 신청→교육·서약→승인→출입 확인까지 이어지는 전체 방문 관리 프로세스를 하나의 시스템으로 통합했습니다.' },
      { type: 'paragraph', text: '방문 유형별 교육·서약·카드 발급 정책을 다르게 적용할 수 있는 구조로 운영 유연성을 높였습니다.' },
    ],
  },
  {
    slug: 'attendance',
    title: '근태현황 및 이상치 소명 시스템',
    category: 'Enterprise System',
    org: 'GlobalZeus',
    period: '2025. 1 — 2025. 3',
    tech: 'Node.js · EJS · MSSQL',
    blocks: [
      { type: 'heading', text: '주요 내용' },
      { type: 'paragraph', text: '선택적 근로제 도입에 맞춰 누락·이상 근무 데이터를 체계적으로 관리하는 시스템을 1인 풀스택으로 구축했습니다.' },
      { type: 'paragraph', text: '관리자가 일일이 확인하는 대신 “임직원 셀프 소명 → 자동 집계 → 부서장 자동 보고” 흐름으로 설계했습니다.' },
      { type: 'paragraph', text: '이상치 정의·분석 로직과 유형별 발생 빈도·추이를 차트로 시각화한 근태 대시보드를 구현했습니다.' },
      { type: 'heading', text: '주요 성과' },
      { type: 'paragraph', text: '소명 데이터를 집계해 근태 보고서를 자동 생성하고, 매월 1일 cron으로 부서장에게 자동 발송되도록 구현했습니다.' },
      { type: 'paragraph', text: '관리자 부담을 줄이면서 이상 근무를 체계적으로 추적·관리할 수 있는 구조를 마련했습니다.' },
    ],
  },
];
